INSERT INTO products (product_id, product_name, product_description, product_category, product_type, product_price, created_at)
VALUES
(21, 'Logitech M510', 'Wireless mouse with ergonomic design.', 'Input Devices', 'Mouse', 29.99, NOW()),
(22, 'Corsair K95 RGB', 'Mechanical gaming keyboard with customizable RGB lighting.', 'Input Devices', 'Keyboard', 49.99, NOW()),
(23, 'Anker PowerCore 10000', 'Portable charger with 10000mAh capacity.', 'Power Accessories', 'Battery', 19.99, NOW()),
(24, 'Anker 4-Port USB 3.0 Hub', 'USB hub for connecting multiple devices.', 'Connectivity Accessories', 'USB Hub', 39.99, NOW()),
(25, 'Logitech C920', 'HD webcam for video conferencing.', 'Output Devices', 'Webcam', 79.99, NOW()),
(26, 'Razer DeathAdder', 'Gaming mouse with high precision.', 'Input Devices', 'Mouse', 49.99, NOW()),
(27, 'SteelSeries Apex 7', 'Mechanical keyboard with customizable RGB.', 'Input Devices', 'Keyboard', 139.99, NOW()),
(28, 'Samsung T5 SSD', 'Portable SSD with fast data transfer.', 'Storage', 'Storage Device', 99.99, NOW()),
(29, 'Apple Magic Mouse', 'Wireless mouse with multi-touch surface.', 'Input Devices', 'Mouse', 79.99, NOW()),
(30, 'HP Spectre x360', '2-in-1 convertible laptop.', 'Computers', 'Laptop', 1299.99, NOW()),
(31, 'Dell UltraSharp 27"', 'High-resolution monitor for detailed graphics.', 'Display', 'Monitor', 599.99, NOW()),
(32, 'ASUS ROG Strix', 'Gaming laptop with powerful performance.', 'Computers', 'Laptop', 1999.99, NOW()),
(33, 'Blue Yeti Microphone', 'Professional USB microphone for streaming.', 'Audio', 'Microphone', 129.99, NOW()),
(34, 'Logitech G Pro', 'Gaming keyboard designed for esports.', 'Input Devices', 'Keyboard', 129.99, NOW()),
(35, 'Sennheiser HD 599', 'High-quality open-back headphones.', 'Audio', 'Headphones', 199.99, NOW()),
(36, 'Wacom Intuos Pro', 'Graphics tablet for artists and designers.', 'Input Devices', 'Graphics Tablet', 349.99, NOW()),
(37, 'Targus USB-C Dock', 'Multi-port USB-C docking station.', 'Connectivity Accessories', 'Docking Station', 149.99, NOW()),
(38, 'ADATA XPG GAMMIX', 'High-speed SSD for gaming.', 'Storage', 'Storage Device', 89.99, NOW()),
(39, 'Razer Kraken', 'Gaming headset with surround sound.', 'Audio', 'Headset', 99.99, NOW()),
(40, 'Netgear Nighthawk', 'High-performance Wi-Fi router.', 'Networking', 'Router', 199.99, NOW()),
(41, 'Oculus Quest 2', 'All-in-one VR headset.', 'Gaming', 'VR Headset', 299.99, NOW()),
(42, 'Amazon Echo', 'Smart speaker with Alexa.', 'Smart Home', 'Speaker', 99.99, NOW()),
(43, 'TP-Link Archer A7', 'Dual band Wi-Fi router.', 'Networking', 'Router', 59.99, NOW()),
(44, 'Apple AirPods', 'Wireless earbuds with excellent sound.', 'Audio', 'Earbuds', 159.99, NOW()),
(45, 'Kindle Paperwhite', 'E-reader with built-in light.', 'E-Readers', 'E-Reader', 129.99, NOW()),
(46, 'Logitech G502', 'Gaming mouse with customizable weights.', 'Input Devices', 'Mouse', 79.99, NOW()),
(47, 'HyperX Cloud II', 'Gaming headset with virtual 7.1 surround sound.', 'Audio', 'Headset', 99.99, NOW()),
(48, 'Samsung Galaxy Tab S7', 'High-performance tablet for work and play.', 'Tablets', 'Tablet', 649.99, NOW()),
(49, 'Dell XPS 15', 'High-end laptop for creatives.', 'Computers', 'Laptop', 1799.99, NOW()),
(50, 'Razer Blade 15', 'Gaming laptop with advanced graphics.', 'Computers', 'Laptop', 2499.99, NOW()),
(51, 'Sony WH-1000XM4', 'Noise-cancelling wireless headphones.', 'Audio', 'Headphones', 349.99, NOW()),
(52, 'Elgato Stream Deck', 'Customizable control pad for streamers.', 'Streaming', 'Accessory', 149.99, NOW()),
(53, 'Logitech G915', 'Gaming keyboard with low-profile mechanical switches.', 'Input Devices', 'Keyboard', 249.99, NOW()),
(54, 'Canon EOS Rebel T7', 'Digital DSLR camera for beginners.', 'Photography', 'Camera', 499.99, NOW()),
(55, 'GoPro HERO9 Black', 'Action camera with advanced features.', 'Photography', 'Camera', 399.99, NOW()),
(56, 'NVIDIA GeForce RTX 3080', 'High-performance graphics card.', 'PC Components', 'Graphics Card', 699.99, NOW()),
(57, 'AMD Ryzen 7 5800X', 'High-performance processor for gaming.', 'PC Components', 'CPU', 449.99, NOW()),
(58, 'Corsair Vengeance LPX', 'High-performance RAM for gaming.', 'PC Components', 'RAM', 79.99, NOW()),
(59, 'Seagate Expansion 2TB', 'External hard drive for additional storage.', 'Storage', 'External HDD', 69.99, NOW()),
(60, 'LG 34WN80C-B', 'Ultrawide monitor for productivity.', 'Display', 'Monitor', 699.99, NOW()),
(61, 'JBL Flip 5', 'Portable Bluetooth speaker with powerful sound.', 'Audio', 'Speaker', 89.99, NOW()),
(62, 'Anker Powerline II', 'Durable Lightning cable.', 'Accessories', 'Cable', 19.99, NOW()),
(63, 'Razer Huntsman Elite', 'Opto-mechanical gaming keyboard.', 'Input Devices', 'Keyboard', 199.99, NOW()),
(64, 'Samsung Galaxy Watch 3', 'Smartwatch with health tracking.', 'Wearables', 'Smartwatch', 399.99, NOW()),
(65, 'DJI Mavic Mini', 'Compact drone with 12MP camera.', 'Photography', 'Drone', 399.99, NOW()),
(66, 'HyperX Alloy FPS', 'Compact mechanical gaming keyboard.', 'Input Devices', 'Keyboard', 79.99, NOW()),
(67, 'Logitech G Pro X Superlight', 'Lightweight gaming mouse.', 'Input Devices', 'Mouse', 149.99, NOW()),
(68, 'Apple iPad Pro 12.9"', 'High-performance tablet for professionals.', 'Tablets', 'Tablet', 1099.99, NOW()),
(69, 'BenQ PD3220U', 'Professional monitor for designers.', 'Display', 'Monitor', 999.99, NOW()),
(70, 'Bose QuietComfort 35 II', 'Noise-cancelling wireless headphones.', 'Audio', 'Headphones', 299.99, NOW()),
(71, 'Razer Thresher Ultimate', 'Wireless gaming headset.', 'Audio', 'Headset', 149.99, NOW()),
(72, 'Apple iMac 24"', 'All-in-one desktop with stunning visuals.', 'Computers', 'Desktop', 1299.99, NOW()),
(73, 'ASUS ProArt PA32UCX', '4K HDR monitor for professionals.', 'Display', 'Monitor', 2999.99, NOW()),
(74, 'Logitech StreamCam', 'Webcam for streaming and video calls.', 'Input Devices', 'Webcam', 149.99, NOW()),
(75, 'Corsair Crystal Series 680X', 'High airflow PC case.', 'PC Components', 'Case', 199.99, NOW()),
(76, 'TP-Link Deco M5', 'Whole home mesh Wi-Fi system.', 'Networking', 'Wi-Fi System', 149.99, NOW()),
(77, 'Dell P2720DC', '27" USB-C monitor with great color accuracy.', 'Display', 'Monitor', 399.99, NOW()),
(78, 'Logitech Z623', '2.1 speaker system with THX certification.', 'Audio', 'Speakers', 149.99, NOW()),
(79, 'HyperX Cloud Stinger', 'Lightweight gaming headset.', 'Audio', 'Headset', 49.99, NOW()),
(80, 'Samsung Galaxy Buds+', 'Wireless earbuds with long battery life.', 'Audio', 'Earbuds', 149.99, NOW()),
(81, 'Philips Electric Kettle', '1.5L electric kettle for quick boiling.', 'Kitchen Appliances', 'Kettle', 2499.99, NOW()),
(82, 'Bajaj 500W Mixer Grinder', 'Multi-functional mixer grinder with three jars.', 'Kitchen Appliances', 'Mixer Grinder', 3499.99, NOW()),
(83, 'Havells Hair Dryer', 'Powerful hair dryer with multiple heat settings.', 'Personal Care', 'Hair Dryer', 1499.99, NOW()),
(84, 'Crompton Greaves Ceiling Fan', 'Energy-efficient ceiling fan with remote control.', 'Home Appliances', 'Fan', 2999.99, NOW()),
(85, 'Philips Beard Trimmer', 'Cordless beard trimmer with precision settings.', 'Personal Care', 'Trimmer', 1999.99, NOW()),
(86, 'Borosil Serving Bowl Set', 'Microwave-safe glass serving bowls.', 'Kitchenware', 'Serving Bowl', 1499.99, NOW()),
(87, 'Pigeon Non-Stick Cookware Set', 'Durable non-stick cookware for healthy cooking.', 'Kitchenware', 'Cookware', 2999.99, NOW()),
(88, 'Tupperware Food Storage Containers', 'Airtight containers for food storage.', 'Kitchenware', 'Storage Containers', 1499.99, NOW()),
(89, 'Kent RO Water Purifier', 'RO water purifier with advanced filtration.', 'Home Appliances', 'Water Purifier', 14999.99, NOW()),
(90, 'Syska LED Bulb', 'Energy-efficient LED bulb with long life.', 'Lighting', 'LED Bulb', 199.99, NOW()),
(91, 'Bajaj 1800W Induction Cooktop', 'Portable induction cooktop for quick meals.', 'Kitchen Appliances', 'Induction Cooktop', 3499.99, NOW()),
(92, 'V-Guard Stabilizer', 'Voltage stabilizer for protecting appliances.', 'Electronics', 'Stabilizer', 1999.99, NOW()),
(93, 'IFB 6.5 kg Fully Automatic Washing Machine', 'Smart washing machine with multiple wash programs.', 'Home Appliances', 'Washing Machine', 25999.99, NOW()),
(94, 'Whirlpool 20L Convection Microwave', 'Microwave oven with grilling function.', 'Kitchen Appliances', 'Microwave', 12999.99, NOW()),
(95, 'Havells Hand Blender', 'Multi-functional hand blender for easy mixing.', 'Kitchen Appliances', 'Blender', 1999.99, NOW()),
(96, 'DuraMax Steel Tool Box', 'Durable tool box for organizing tools.', 'Hardware', 'Tool Box', 1999.99, NOW()),
(97, 'Philips Electric Rice Cooker', 'Smart rice cooker with steaming tray.', 'Kitchen Appliances', 'Rice Cooker', 2499.99, NOW()),
(98, 'Samsung 1.5 Ton Split AC', 'Energy-efficient air conditioner for cooling.', 'Home Appliances', 'Air Conditioner', 34999.99, NOW()),
(99, 'Oppo F19 Smartphone', 'Affordable smartphone with good features.', 'Mobile', 'Smartphone', 17999.99, NOW()),
(100, 'Adidas Yoga Mat', 'Non-slip yoga mat for fitness enthusiasts.', 'Fitness', 'Yoga Mat', 1299.99, NOW()),
(101, 'Havells Ceiling Fan', 'Stylish ceiling fan with energy-efficient motor.', 'Home Appliances', 'Fan', 2999.99, NOW()),
(102, 'Philips Nose Trimmer', 'Cordless nose trimmer for precise grooming.', 'Personal Care', 'Trimmer', 1299.99, NOW()),
(103, 'Tata Power UPS', 'Uninterruptible power supply for home and office.', 'Electronics', 'UPS', 4999.99, NOW()),
(104, 'Borosil Glass Serving Set', 'Elegant glass serving set for dining.', 'Kitchenware', 'Serving Set', 1999.99, NOW()),
(105, 'Prestige Induction Cooktop', 'Energy-efficient induction cooktop with touch control.', 'Kitchen Appliances', 'Induction Cooktop', 2999.99, NOW()),
(106, 'Kent Mini Water Purifier', 'Compact water purifier with UV filtration.', 'Home Appliances', 'Water Purifier', 7999.99, NOW()),
(107, 'Panasonic 50-inch Smart TV', 'Smart TV with 4K resolution and Wi-Fi.', 'Electronics', 'Television', 49999.99, NOW()),
(108, 'Crompton Greaves Exhaust Fan', 'Efficient exhaust fan for ventilation.', 'Home Appliances', 'Exhaust Fan', 1499.99, NOW()),
(109, 'Sony Bluetooth Speaker', 'Portable speaker with rich sound quality.', 'Audio', 'Speaker', 8999.99, NOW()),
(110, 'Himalaya Facial Kit', 'Herbal facial kit for glowing skin.', 'Personal Care', 'Facial Kit', 499.99, NOW()),
(111, 'Philips Water Heater', 'Instant water heater with safety features.', 'Home Appliances', 'Water Heater', 4999.99, NOW()),
(112, 'Nivia Sports Bag', 'Durable sports bag for gym and travel.', 'Sports', 'Bag', 1499.99, NOW()),
(113, 'AquaGuard Water Purifier', 'Water purifier with advanced RO technology.', 'Home Appliances', 'Water Purifier', 12999.99, NOW()),
(114, 'Fire-Boltt Smartwatch', 'Fitness smartwatch with heart rate monitor.', 'Wearables', 'Smartwatch', 3999.99, NOW()),
(115, 'Karcher K2 Pressure Washer', 'High-pressure washer for cleaning vehicles and surfaces.', 'Hardware', 'Pressure Washer', 12999.99, NOW()),
(116, 'Tupperware Kitchen Set', 'Comprehensive kitchen storage set.', 'Kitchenware', 'Storage Set', 2999.99, NOW()),
(117, 'Croma Home Theater System', 'Surround sound system for home entertainment.', 'Audio', 'Home Theater', 19999.99, NOW()),
(118, 'Pigeon 3-Liter Pressure Cooker', 'Durable pressure cooker for quick cooking.', 'Kitchen Appliances', 'Pressure Cooker', 2499.99, NOW()),
(119, 'Bajaj Ceiling Fan', 'Energy-efficient ceiling fan with remote control.', 'Home Appliances', 'Fan', 2499.99, NOW()),
(120, 'Remington Hair Straightener', 'Fast heating straightener for smooth styling.', 'Personal Care', 'Straightener', 2999.99, NOW()),
(121, 'Havells Electric Tandoor', 'Electric tandoor for quick grilling at home.', 'Kitchen Appliances', 'Tandoor', 3999.99, NOW()),
(122, 'Lifelong Water Dispenser', 'Hot and cold water dispenser for home use.', 'Home Appliances', 'Water Dispenser', 7999.99, NOW()),
(123, 'Philips Hair Curler', 'Curling iron for beautiful curls.', 'Personal Care', 'Curler', 2999.99, NOW()),
(124, 'Schneider Electric Smart Plug', 'Smart plug for controlling devices remotely.', 'Electronics', 'Smart Home', 1999.99, NOW()),
(125, 'Smart LED Strip Lights', 'Color-changing LED strip for decoration.', 'Lighting', 'LED Strip', 999.99, NOW()),
(126, 'Tata Sky Set-Top Box', 'DTH connection with a wide range of channels.', 'Electronics', 'Set-Top Box', 3999.99, NOW()),
(127, 'Havells Smart Plug', 'Wi-Fi enabled smart plug for home automation.', 'Electronics', 'Smart Plug', 1499.99, NOW()),
(128, 'Dove Body Wash', 'Nourishing body wash for soft skin.', 'Personal Care', 'Body Wash', 299.99, NOW()),
(129, 'Puma Sports Shoes', 'Comfortable sports shoes for running.', 'Footwear', 'Shoes', 3999.99, NOW()),
(130, 'Adidas Gym Bag', 'Durable gym bag for workouts.', 'Sports', 'Bag', 1499.99, NOW()),
(131, 'Inalsa Food Processor', 'Multi-functional food processor for easy cooking.', 'Kitchen Appliances', 'Food Processor', 5499.99, NOW()),
(132, 'Samsung 32-inch LED TV', 'HD Ready LED TV for home entertainment.', 'Electronics', 'Television', 22999.99, NOW()),
(133, 'Crompton Greaves Table Lamp', 'Stylish table lamp for home decor.', 'Lighting', 'Lamp', 899.99, NOW()),
(134, 'Sony PlayStation 5', 'Latest gaming console with advanced features.', 'Gaming', 'Console', 49999.99, NOW()),
(135, 'Havells Room Heater', 'Compact room heater for instant warmth.', 'Home Appliances', 'Heater', 2499.99, NOW()),
(136, 'Panasonic Cordless Phone', 'Cordless phone with caller ID.', 'Electronics', 'Phone', 2999.99, NOW()),
(137, 'Havells Air Purifier', 'Air purifier with HEPA filter for clean air.', 'Home Appliances', 'Air Purifier', 9999.99, NOW()),
(138, 'Remington Hair Dryer', 'Powerful hair dryer with multiple settings.', 'Personal Care', 'Hair Dryer', 1999.99, NOW()),
(139, 'Philips Smart Bulb', 'Wi-Fi enabled smart bulb for remote control.', 'Lighting', 'Smart Bulb', 999.99, NOW()),
(140, 'Kook N Keech Backpack', 'Stylish and functional backpack for daily use.', 'Fashion', 'Backpack', 999.99, NOW()),
(141, 'Realme Buds Q', 'Wireless earbuds with excellent sound quality.', 'Audio', 'Earbuds', 1999.99, NOW()),
(142, 'Nivia Football', 'Durable football for outdoor games.', 'Sports', 'Football', 799.99, NOW()),
(143, 'Fastrack Sunglasses', 'Trendy sunglasses for summer days.', 'Fashion', 'Sunglasses', 1299.99, NOW()),
(144, 'Himalaya Herbal Shampoo', 'Natural shampoo for healthy hair.', 'Personal Care', 'Shampoo', 299.99, NOW()),
(145, 'Tata Power UPS', 'Uninterruptible power supply for computers.', 'Electronics', 'UPS', 3999.99, NOW()),
(146, 'Philips Travel Hair Dryer', 'Compact travel hair dryer for on-the-go styling.', 'Personal Care', 'Hair Dryer', 1499.99, NOW()),
(147, 'Inalsa Mixer Grinder', 'High-performance mixer grinder with multiple jars.', 'Kitchen Appliances', 'Mixer Grinder', 2999.99, NOW()),
(148, 'Borosil Glass Mixing Bowl', 'Heat-resistant glass mixing bowl for cooking.', 'Kitchenware', 'Mixing Bowl', 799.99, NOW()),
(149, 'LG 1.5 Ton AC', 'Split AC with cooling and heating features.', 'Home Appliances', 'Air Conditioner', 38999.99, NOW()),
(150, 'Ambrane Power Bank', 'Portable power bank for charging devices on the go.', 'Electronics', 'Power Bank', 1499.99, NOW()),
(151, 'Bosch Car Battery', 'High-performance battery for reliable starting.', 'Automotive', 'Car Battery', 6999.99, NOW()),
(152, 'Hella Fog Lights', 'LED fog lights for improved visibility.', 'Automotive', 'Fog Lights', 2999.99, NOW()),
(153, 'Motul Engine Oil', 'High-quality synthetic engine oil for smooth performance.', 'Automotive', 'Engine Oil', 2499.99, NOW()),
(154, 'MRF Tyres', 'Durable tyres for all weather conditions.', 'Automotive', 'Tyres', 4999.99, NOW()),
(155, 'Castrol Brake Fluid', 'High-performance brake fluid for safety.', 'Automotive', 'Brake Fluid', 999.99, NOW()),
(156, 'Valvoline Coolant', 'Antifreeze coolant for engine protection.', 'Automotive', 'Coolant', 899.99, NOW()),
(157, 'Stanley Tool Kit', 'Comprehensive tool kit for automotive repairs.', 'Automotive', 'Tool Kit', 3999.99, NOW()),
(158, 'Philips Car Headlight Bulbs', 'Bright halogen headlight bulbs for better visibility.', 'Automotive', 'Headlight Bulbs', 1499.99, NOW()),
(159, 'AmazonBasics Car Cover', 'Durable car cover for protection from elements.', 'Automotive', 'Car Cover', 1999.99, NOW()),
(160, 'Hawk Brake Pads', 'High-quality brake pads for improved stopping power.', 'Automotive', 'Brake Pads', 2499.99, NOW()),
(161, '3M Car Wax', 'Protective wax for a shiny finish.', 'Automotive', 'Car Wax', 1299.99, NOW()),
(162, 'Cannon Car Vacuum Cleaner', 'Portable vacuum cleaner for car interiors.', 'Automotive', 'Vacuum Cleaner', 2499.99, NOW()),
(163, 'AmazonBasics Jumper Cables', 'Heavy-duty jumper cables for emergency starts.', 'Automotive', 'Jumper Cables', 899.99, NOW()),
(164, 'Zebronics Car Speakers', 'High-quality speakers for an immersive sound experience.', 'Automotive', 'Speakers', 3499.99, NOW()),
(165, 'Sunex Car Ramps', 'Durable ramps for easy access to the undercarriage.', 'Automotive', 'Ramps', 2999.99, NOW()),
(166, 'CarGo Car Organizer', 'Multi-functional organizer for car interiors.', 'Automotive', 'Organizer', 1499.99, NOW()),
(167, 'Sylvania LED Car Lights', 'Energy-efficient LED lights for car interiors.', 'Automotive', 'Interior Lights', 1499.99, NOW()),
(168, 'Steelmate Parking Sensor', 'Parking sensor system for safer parking.', 'Automotive', 'Parking Sensor', 4999.99, NOW()),
(169, 'CarMate Phone Holder', 'Universal phone holder for car dashboards.', 'Automotive', 'Phone Holder', 799.99, NOW()),
(170, 'K&N Air Filter', 'High-performance air filter for improved engine efficiency.', 'Automotive', 'Air Filter', 2999.99, NOW()),
(171, 'Cobra Radar Detector', 'Radar detector for safer driving.', 'Automotive', 'Radar Detector', 9999.99, NOW()),
(172, 'Armor All Protectant', 'Protectant for dashboards and interiors.', 'Automotive', 'Protectant', 599.99, NOW()),
(173, 'Pioneer Car Stereo', 'High-quality car stereo with Bluetooth connectivity.', 'Automotive', 'Car Stereo', 7999.99, NOW()),
(174, 'Hankook Tyres', 'Performance tyres for enhanced grip.', 'Automotive', 'Tyres', 5999.99, NOW()),
(175, 'Meguiar’s Ultimate Quik Wax', 'Quick wax for a brilliant shine.', 'Automotive', 'Car Wax', 1299.99, NOW()),
(176, 'Snap-on Tool Chest', 'Heavy-duty tool chest for organizing tools.', 'Automotive', 'Tool Chest', 19999.99, NOW()),
(177, 'Kraft Automotive Jumper Starter', 'Portable battery jump starter.', 'Automotive', 'Jump Starter', 3999.99, NOW()),
(178, 'Bully Hitch Receiver', 'Durable hitch receiver for towing.', 'Automotive', 'Hitch', 4999.99, NOW()),
(179, 'Chemical Guys Car Wash Kit', 'Complete car wash kit for a clean finish.', 'Automotive', 'Wash Kit', 2999.99, NOW()),
(180, 'Noah Car Sunshade', 'UV protection sunshade for windshields.', 'Automotive', 'Sunshade', 999.99, NOW()),
(181, 'Trico Wiper Blades', 'Durable wiper blades for clear visibility.', 'Automotive', 'Wiper Blades', 1299.99, NOW()),
(182, 'Hella LED Work Light', 'Powerful LED work light for repairs.', 'Automotive', 'Work Light', 2999.99, NOW()),
(183, 'Turtle Wax Interior Cleaner', 'Cleaner for car interiors.', 'Automotive', 'Cleaner', 799.99, NOW()),
(184, 'Dodge Heavy Duty Winch', 'Powerful winch for off-road vehicles.', 'Automotive', 'Winch', 14999.99, NOW()),
(185, 'Meguiar’s Clay Bar Kit', 'Clay bar kit for a smooth finish.', 'Automotive', 'Clay Bar Kit', 1999.99, NOW()),
(186, 'Bushwacker Fender Flares', 'Durable fender flares for off-road vehicles.', 'Automotive', 'Fender Flares', 5999.99, NOW()),
(187, 'Black & Decker Cordless Drill', 'Powerful drill for automotive projects.', 'Automotive', 'Cordless Drill', 4999.99, NOW()),
(188, 'Smittybilt Seat Covers', 'Durable seat covers for trucks and SUVs.', 'Automotive', 'Seat Covers', 2999.99, NOW()),
(189, 'Carhartt Floor Mats', 'Heavy-duty floor mats for vehicle protection.', 'Automotive', 'Floor Mats', 2999.99, NOW()),
(190, 'HitchMate Cargo Carrier', 'Cargo carrier for extra storage.', 'Automotive', 'Cargo Carrier', 4999.99, NOW()),
(191, 'Duralast Battery Charger', 'Fast-charging battery charger for vehicles.', 'Automotive', 'Battery Charger', 2999.99, NOW()),
(192, 'WeatherTech Floor Liners', 'All-weather floor liners for vehicle protection.', 'Automotive', 'Floor Liners', 4999.99, NOW()),
(193, 'Champion Spark Plugs', 'High-performance spark plugs for better ignition.', 'Automotive', 'Spark Plugs', 1299.99, NOW()),
(194, 'Rugged Ridge Off-Road Lights', 'Bright LED lights for off-road adventures.', 'Automotive', 'Off-Road Lights', 3999.99, NOW()),
(195, 'Ravenox Tow Strap', 'Heavy-duty tow strap for pulling vehicles.', 'Automotive', 'Tow Strap', 999.99, NOW()),
(196, 'Smittybilt Winch Mount', 'Sturdy winch mount for off-road vehicles.', 'Automotive', 'Winch Mount', 2499.99, NOW()),
(197, 'Pyle Bluetooth Car Kit', 'Bluetooth kit for hands-free calls.', 'Automotive', 'Bluetooth Kit', 1499.99, NOW()),
(198, 'JVC Car Amplifier', 'High-power amplifier for enhanced sound quality.', 'Automotive', 'Amplifier', 6999.99, NOW()),
(199, 'Lucas Oil Stabilizer', 'Engine oil stabilizer for reduced wear.', 'Automotive', 'Oil Stabilizer', 1299.99, NOW()),
(200, 'Torklift International Tie Down Anchors', 'Heavy-duty tie down anchors for secure loads.', 'Automotive', 'Tie Down Anchors', 1999.99, NOW()),
(201, 'The Alchemist', 'A novel by Paulo Coelho about a shepherd’s journey.', 'Books and Media', 'Book', 399.99, NOW()),
(202, 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari’s exploration of human history.', 'Books and Media', 'Book', 599.99, NOW()),
(203, 'Becoming', 'Michelle Obama’s memoir about her life and experiences.', 'Books and Media', 'Book', 499.99, NOW()),
(204, 'The Power of Habit', 'A guide to understanding habits and how to change them.', 'Books and Media', 'Book', 499.99, NOW()),
(205, 'The Silent Patient', 'A psychological thriller by Alex Michaelides.', 'Books and Media', 'Book', 399.99, NOW()),
(206, 'Atomic Habits', 'James Clear’s guide to building good habits.', 'Books and Media', 'Book', 499.99, NOW()),
(207, 'Educated', 'Tara Westover’s memoir about her quest for knowledge.', 'Books and Media', 'Book', 499.99, NOW()),
(208, 'The Great Gatsby', 'F. Scott Fitzgerald’s classic novel set in the Jazz Age.', 'Books and Media', 'Book', 299.99, NOW()),
(209, 'Harry Potter and the Sorcerer\'s Stone', 'The first book in J.K. Rowling’s beloved series.', 'Books and Media', 'Book', 599.99, NOW()),
(210, 'The Catcher in the Rye', 'J.D. Salinger’s iconic novel about teenage angst.', 'Books and Media', 'Book', 399.99, NOW()),
(211, 'The Girl on the Train', 'A psychological thriller by Paula Hawkins.', 'Books and Media', 'Book', 499.99, NOW()),
(212, '1984', 'George Orwell’s dystopian novel about totalitarianism.', 'Books and Media', 'Book', 299.99, NOW()),
(213, 'Pride and Prejudice', 'Jane Austen’s classic romantic novel.', 'Books and Media', 'Book', 399.99, NOW()),
(214, 'The Diary of a Young Girl', 'Anne Frank’s poignant account of life in hiding.', 'Books and Media', 'Book', 499.99, NOW()),
(215, 'The Subtle Art of Not Giving a F*ck', 'Mark Manson’s unconventional self-help book.', 'Books and Media', 'Book', 499.99, NOW()),
(216, 'The Hobbit', 'J.R.R. Tolkien’s fantasy adventure novel.', 'Books and Media', 'Book', 399.99, NOW()),
(217, 'To Kill a Mockingbird', 'Harper Lee’s Pulitzer Prize-winning novel.', 'Books and Media', 'Book', 499.99, NOW()),
(218, 'The Fault in Our Stars', 'A novel by John Green about young love.', 'Books and Media', 'Book', 399.99, NOW()),
(219, 'A Brief History of Time', 'Stephen Hawking’s exploration of cosmology.', 'Books and Media', 'Book', 699.99, NOW()),
(220, 'The Art of War', 'Sun Tzu’s ancient treatise on strategy.', 'Books and Media', 'Book', 299.99, NOW()),
(221, 'The Book Thief', 'A novel by Markus Zusak set in Nazi Germany.', 'Books and Media', 'Book', 499.99, NOW()),
(222, 'The Immortal Life of Henrietta Lacks', 'A true story about medical ethics and race.', 'Books and Media', 'Book', 499.99, NOW()),
(223, 'Gone Girl', 'A thriller by Gillian Flynn about a marriage gone wrong.', 'Books and Media', 'Book', 499.99, NOW()),
(224, 'Dune', 'Frank Herbert’s epic science fiction novel.', 'Books and Media', 'Book', 599.99, NOW()),
(225, 'The Hunger Games', 'Suzanne Collins’ dystopian novel about survival.', 'Books and Media', 'Book', 499.99, NOW()),
(226, 'Where the Crawdads Sing', 'A novel by Delia Owens about isolation and love.', 'Books and Media', 'Book', 599.99, NOW()),
(227, 'The Alchemist’s Daughter', 'A fantasy novel about a young woman’s quest.', 'Books and Media', 'Book', 499.99, NOW()),
(228, 'The 7 Habits of Highly Effective People', 'Stephen Covey’s self-help classic.', 'Books and Media', 'Book', 499.99, NOW()),
(229, 'The Grapes of Wrath', 'John Steinbeck’s powerful depiction of the Great Depression.', 'Books and Media', 'Book', 599.99, NOW()),
(230, 'The Kite Runner', 'Khaled Hosseini’s tale of friendship and redemption.', 'Books and Media', 'Book', 499.99, NOW()),
(231, 'Life of Pi', 'Yann Martel’s adventure of survival at sea.', 'Books and Media', 'Book', 499.99, NOW()),
(232, 'The Road', 'Cormac McCarthy’s post-apocalyptic novel.', 'Books and Media', 'Book', 599.99, NOW()),
(233, 'The Night Circus', 'Erin Morgenstern’s fantasy about a magical competition.', 'Books and Media', 'Book', 599.99, NOW()),
(234, 'Little Fires Everywhere', 'Celeste Ng’s novel about family and community.', 'Books and Media', 'Book', 499.99, NOW()),
(235, 'Normal People', 'Sally Rooney’s exploration of love and friendship.', 'Books and Media', 'Book', 499.99, NOW()),
(236, 'Circe', 'Madeline Miller’s retelling of the story of Circe.', 'Books and Media', 'Book', 599.99, NOW()),
(237, 'The Vanishing Half', 'A novel by Brit Bennett about identity and family.', 'Books and Media', 'Book', 499.99, NOW()),
(238, 'Anxious People', 'Fredrik Backman’s novel about a bank robbery gone wrong.', 'Books and Media', 'Book', 499.99, NOW()),
(239, 'The Midnight Library', 'A novel by Matt Haig about life choices.', 'Books and Media', 'Book', 499.99, NOW()),
(240, 'Malibu Rising', 'Taylor Jenkins Reid’s story about family and fame.', 'Books and Media', 'Book', 499.99, NOW()),
(241, 'The Silent Patient', 'A psychological thriller about a woman who stops speaking.', 'Books and Media', 'Book', 499.99, NOW()),
(242, 'The Guest List', 'A thriller set at a wedding on a remote Irish island.', 'Books and Media', 'Book', 599.99, NOW()),
(243, 'Eleanor Oliphant Is Completely Fine', 'A novel about a socially awkward woman and her journey.', 'Books and Media', 'Book', 499.99, NOW()),
(244, 'The Woman in the Window', 'A psychological thriller about an agoraphobic woman.', 'Books and Media', 'Book', 499.99, NOW()),
(245, 'Before the Coffee Gets Cold', 'A unique tale about time travel in a café.', 'Books and Media', 'Book', 399.99, NOW()),
(246, 'Station Eleven', 'A post-apocalyptic novel about a traveling theater troupe.', 'Books and Media', 'Book', 599.99, NOW()),
(247, 'The Seven Husbands of Evelyn Hugo', 'A historical fiction novel about a reclusive Hollywood star.', 'Books and Media', 'Book', 499.99, NOW()),
(248, 'A Man Called Ove', 'A heartwarming story about a grumpy old man.', 'Books and Media', 'Book', 499.99, NOW()),
(249, 'The Light We Lost', 'A love story that spans years and continents.', 'Books and Media', 'Book', 499.99, NOW()),
(250, 'The Tattooist of Auschwitz', 'A poignant love story set during World War II.', 'Books and Media', 'Book', 499.99, NOW()),
(251, 'Avery Binder', 'Durable 1-inch binder for organizing documents.', 'Office Supplies', 'Binder', 299.99, NOW()),
(252, 'Pilot G2 Gel Pens', 'Smooth-writing gel pens for everyday use.', 'Office Supplies', 'Pens', 199.99, NOW()),
(253, 'Post-it Notes', 'Brightly colored sticky notes for reminders and organization.', 'Office Supplies', 'Sticky Notes', 149.99, NOW()),
(254, 'Staples Heavy Duty Stapler', 'Durable stapler for heavy-duty tasks.', 'Office Supplies', 'Stapler', 599.99, NOW()),
(255, 'BIC Mechanical Pencils', 'Precision mechanical pencils for writing and drawing.', 'Office Supplies', 'Pencils', 299.99, NOW()),
(256, 'Five Star Notebook', 'Durable notebook with pockets for easy organization.', 'Office Supplies', 'Notebook', 399.99, NOW()),
(257, 'HP Printer Paper', 'High-quality printer paper for professional documents.', 'Office Supplies', 'Paper', 499.99, NOW()),
(258, 'Fellowes Paper Shredder', 'Cross-cut shredder for secure document disposal.', 'Office Supplies', 'Shredder', 6999.99, NOW()),
(259, 'Scotch Tape Dispenser', 'Desktop tape dispenser for easy access.', 'Office Supplies', 'Tape Dispenser', 199.99, NOW()),
(260, 'Swingline Heavy Duty Hole Punch', 'Punches up to 40 sheets for multiple documents.', 'Office Supplies', 'Hole Punch', 899.99, NOW()),
(261, 'Dixon Ticonderoga Pencils', 'Premium wood-cased pencils for writing.', 'Office Supplies', 'Pencils', 199.99, NOW()),
(262, 'Crayola Markers', 'Washable markers in assorted colors.', 'Office Supplies', 'Markers', 399.99, NOW()),
(263, 'Moleskine Classic Notebook', 'Luxury notebook for notes and sketches.', 'Office Supplies', 'Notebook', 899.99, NOW()),
(264, 'Desk Organizer', 'Multi-compartment organizer for keeping your desk tidy.', 'Office Supplies', 'Desk Organizer', 599.99, NOW()),
(265, 'Brother Label Maker', 'Compact label maker for home or office use.', 'Office Supplies', 'Label Maker', 2999.99, NOW()),
(266, 'Avery Address Labels', 'Self-adhesive labels for mailing and organization.', 'Office Supplies', 'Labels', 149.99, NOW()),
(267, 'Pacon Construction Paper', 'Vibrant construction paper for arts and crafts.', 'Office Supplies', 'Construction Paper', 199.99, NOW()),
(268, 'Wilson Jones Sheet Protectors', 'Durable sheet protectors for presentations.', 'Office Supplies', 'Sheet Protectors', 299.99, NOW()),
(269, 'Lorell Mobile File Cabinet', 'Rolling file cabinet for office organization.', 'Furniture', 'File Cabinet', 6999.99, NOW()),
(270, 'Flash Furniture Office Chair', 'Ergonomic office chair with adjustable height.', 'Furniture', 'Office Chair', 4999.99, NOW()),
(271, 'Bush Furniture L Shaped Desk', 'Spacious L-shaped desk for home office.', 'Furniture', 'Desk', 14999.99, NOW()),
(272, 'Safco Sit-Stand Desk Converter', 'Adjustable desk converter for standing work.', 'Furniture', 'Desk Converter', 7999.99, NOW()),
(273, 'Lorell Conference Table', 'Large conference table for meetings.', 'Furniture', 'Conference Table', 19999.99, NOW()),
(274, 'Sauder Computer Desk', 'Stylish computer desk for small spaces.', 'Furniture', 'Computer Desk', 5999.99, NOW()),
(275, 'Altra Industrial Storage Cabinet', 'Storage cabinet for office supplies.', 'Furniture', 'Storage Cabinet', 4999.99, NOW()),
(276, 'Coaster Home Office Chair', 'Comfortable office chair with lumbar support.', 'Furniture', 'Office Chair', 3999.99, NOW()),
(277, 'Zinus Modern Studio Collection Desk', 'Minimalist desk for contemporary offices.', 'Furniture', 'Desk', 6999.99, NOW()),
(278, 'Staples Folding Table', 'Portable folding table for events or office use.', 'Furniture', 'Folding Table', 2999.99, NOW()),
(279, 'AmazonBasics Rolling Storage Cart', 'Multi-tier cart for easy storage.', 'Furniture', 'Storage Cart', 2999.99, NOW()),
(280, 'Flash Furniture Mesh Office Chair', 'Breathable mesh chair for all-day comfort.', 'Furniture', 'Office Chair', 4999.99, NOW()),
(281, 'Poppin Desk Organizer Set', 'Colorful desk organizers for workspace organization.', 'Office Supplies', 'Desk Organizer', 1999.99, NOW()),
(282, 'Sharpie Permanent Markers', 'Bold permanent markers for labeling.', 'Office Supplies', 'Markers', 299.99, NOW()),
(283, 'Rhodia Webnotebook', 'High-quality notebook for notes and sketches.', 'Office Supplies', 'Notebook', 899.99, NOW()),
(284, 'Avery Presentation Folders', 'Professional presentation folders for reports.', 'Office Supplies', 'Presentation Folder', 399.99, NOW()),
(285, 'AmazonBasics Whiteboard', 'Magnetic whiteboard for presentations and notes.', 'Office Supplies', 'Whiteboard', 2999.99, NOW()),
(286, 'Hammermill Copy Paper', 'Versatile copy paper for everyday use.', 'Office Supplies', 'Paper', 499.99, NOW()),
(287, 'Smead Hanging File Folders', 'Durable hanging folders for organization.', 'Office Supplies', 'File Folders', 299.99, NOW()),
(288, 'Desk Clock', 'Sleek desk clock for time management.', 'Furniture', 'Clock', 1999.99, NOW()),
(289, 'Paper Mate InkJoy Pens', 'Smooth ink pens for writing and drawing.', 'Office Supplies', 'Pens', 299.99, NOW()),
(290, 'Quartet Cork Board', 'Cork board for pinning notes and reminders.', 'Office Supplies', 'Cork Board', 1999.99, NOW()),
(291, 'Eagle Locking File Cabinet', 'Secure locking file cabinet for documents.', 'Furniture', 'File Cabinet', 9999.99, NOW()),
(292, 'Urban Shop Desk', 'Stylish desk perfect for home offices.', 'Furniture', 'Desk', 4999.99, NOW()),
(293, 'Office Star Executive Chair', 'Comfortable executive chair with adjustable features.', 'Furniture', 'Executive Chair', 6999.99, NOW()),
(294, 'Uline Shipping Labels', 'High-quality shipping labels for parcels.', 'Office Supplies', 'Shipping Labels', 599.99, NOW()),
(295, 'Bostitch Electric Stapler', 'Electric stapler for quick and easy stapling.', 'Office Supplies', 'Stapler', 2999.99, NOW()),
(296, 'Marble Desk Organizer', 'Elegant desk organizer for a sophisticated look.', 'Office Supplies', 'Desk Organizer', 1299.99, NOW()),
(297, '3M Post-it Super Sticky Notes', 'Extra sticky notes for better adhesion.', 'Office Supplies', 'Sticky Notes', 249.99, NOW()),
(298, 'Ergonomic Footrest', 'Adjustable footrest for better posture.', 'Furniture', 'Footrest', 2999.99, NOW()),
(299, 'Staples Task Chair', 'Affordable task chair for office use.', 'Furniture', 'Task Chair', 2999.99, NOW()),
(300, 'Self-Adhesive Velcro Dots', 'Perfect for crafting and organizing.', 'Office Supplies', 'Velcro Dots', 199.99, NOW()),
(301, 'Rubber Bands', 'Assorted sizes for office use and organization.', 'Office Supplies', 'Rubber Bands', 199.99, NOW()),
(302, 'Toner Cartridge', 'Compatible toner cartridge for laser printers.', 'Office Supplies', 'Toner', 2499.99, NOW()),
(303, 'Clipboards', 'Durable clipboards for holding documents.', 'Office Supplies', 'Clipboard', 199.99, NOW()),
(304, 'Dry Erase Markers', 'Bold markers for whiteboards.', 'Office Supplies', 'Markers', 299.99, NOW()),
(305, 'Corner Desk', 'L-shaped corner desk for maximizing space.', 'Furniture', 'Desk', 7999.99, NOW()),
(306, 'Desk Lamp', 'Adjustable desk lamp with LED lighting.', 'Furniture', 'Desk Lamp', 2499.99, NOW()),
(307, 'Office Supply Caddy', 'Multi-compartment caddy for organizing supplies.', 'Office Supplies', 'Caddy', 499.99, NOW()),
(308, 'Vinyl Gloves', 'Disposable gloves for office use or medical purposes.', 'Office Supplies', 'Gloves', 499.99, NOW()),
(309, '3M Command Hooks', 'Damage-free hanging solution for offices.', 'Office Supplies', 'Hooks', 299.99, NOW()),
(310, 'Folding Chair', 'Lightweight folding chair for additional seating.', 'Furniture', 'Folding Chair', 1999.99, NOW()),
(311, 'Cork Coasters', 'Natural cork coasters for office desks.', 'Office Supplies', 'Coasters', 299.99, NOW()),
(312, 'Screen Cleaner Kit', 'Cleaner and microfiber cloth for screens.', 'Office Supplies', 'Cleaner Kit', 499.99, NOW()),
(313, 'Desk Organizer Tray', 'Stackable trays for organizing papers.', 'Office Supplies', 'Tray', 599.99, NOW()),
(314, 'Portable Laptop Stand', 'Adjustable stand for laptops.', 'Furniture', 'Laptop Stand', 2999.99, NOW()),
(315, 'Ergonomic Keyboard', 'Keyboard designed for comfort and efficiency.', 'Office Supplies', 'Keyboard', 1999.99, NOW()),
(316, 'Storage Bin', 'Plastic storage bin for office supplies.', 'Office Supplies', 'Storage Bin', 399.99, NOW()),
(317, 'Mini Whiteboard', 'Small whiteboard for personal notes.', 'Office Supplies', 'Whiteboard', 999.99, NOW()),
(318, 'Printer Stand', 'Elevated stand for printers and office equipment.', 'Furniture', 'Printer Stand', 2999.99, NOW()),
(319, 'Wall Calendar', 'Monthly wall calendar for scheduling.', 'Office Supplies', 'Calendar', 399.99, NOW()),
(320, 'Mechanical Desk Clock', 'Traditional clock for desk use.', 'Furniture', 'Desk Clock', 999.99, NOW()),
(321, 'Watercolor Paper', 'Specialized paper for watercolor painting.', 'Office Supplies', 'Art Paper', 499.99, NOW()),
(322, 'Expandable File Folder', 'Folder with expandable sections for organization.', 'Office Supplies', 'File Folder', 399.99, NOW()),
(323, 'Desk Pad', 'Protective desk pad for smooth writing surface.', 'Office Supplies', 'Desk Pad', 999.99, NOW()),
(324, 'Sofa Table', 'Stylish table for living room or office.', 'Furniture', 'Table', 6999.99, NOW()),
(325, 'Conference Room Chairs', 'Comfortable seating for meetings.', 'Furniture', 'Chairs', 4999.99, NOW()),
(326, 'Cable Management Clips', 'Clips for organizing cables on desks.', 'Office Supplies', 'Cable Clips', 199.99, NOW()),
(327, 'Biodegradable Ballpoint Pens', 'Eco-friendly pens for everyday writing.', 'Office Supplies', 'Pens', 399.99, NOW()),
(328, 'Dry Erase Board Eraser', 'Eraser for whiteboards.', 'Office Supplies', 'Eraser', 199.99, NOW()),
(329, 'Personal Safe', 'Lockable safe for securing documents and valuables.', 'Furniture', 'Safe', 9999.99, NOW()),
(330, 'Round Conference Table', 'Spacious round table for meetings.', 'Furniture', 'Conference Table', 14999.99, NOW()),
(331, 'Adjustable Drafting Chair', 'Chair designed for artists and architects.', 'Furniture', 'Drafting Chair', 5999.99, NOW()),
(332, 'Portable File Box', 'Carry case for documents and files.', 'Office Supplies', 'File Box', 899.99, NOW()),
(333, 'Cardstock Paper', 'Heavyweight paper for printing and crafting.', 'Office Supplies', 'Cardstock', 299.99, NOW()),
(334, 'Printer Paper Ream', 'Ream of high-quality printer paper.', 'Office Supplies', 'Paper', 499.99, NOW()),
(335, 'Executive Desk', 'Large desk for home or office use.', 'Furniture', 'Desk', 12999.99, NOW()),
(336, 'Lateral File Cabinet', 'Horizontal file cabinet for documents.', 'Furniture', 'File Cabinet', 7999.99, NOW()),
(337, 'Mobile Whiteboard', 'Rolling whiteboard for presentations.', 'Office Supplies', 'Whiteboard', 6999.99, NOW()),
(338, 'Magnetic Tape', 'Adhesive tape for crafting and organization.', 'Office Supplies', 'Tape', 299.99, NOW()),
(339, 'Desktop Calendar', 'Daily calendar for planning.', 'Office Supplies', 'Calendar', 299.99, NOW()),
(340, 'Acrylic Desk Organizer', 'Clear organizer for easy visibility.', 'Office Supplies', 'Desk Organizer', 999.99, NOW()),
(341, 'Electric Kettle', 'Fast boiling kettle for office use.', 'Furniture', 'Kettle', 2999.99, NOW()),
(342, 'Velcro Cable Ties', 'Reusable ties for organizing cables.', 'Office Supplies', 'Cable Ties', 199.99, NOW()),
(343, 'Whiteboard Markers', 'Assorted colors for use on whiteboards.', 'Office Supplies', 'Markers', 299.99, NOW()),
(344, 'Freestanding Shelf', 'Bookshelf for office or home use.', 'Furniture', 'Shelf', 4999.99, NOW()),
(345, 'Desk Fan', 'Compact fan for personal cooling.', 'Furniture', 'Fan', 1999.99, NOW()),
(346, 'Laptop Sleeve', 'Padded sleeve for protecting laptops.', 'Office Supplies', 'Laptop Sleeve', 999.99, NOW()),
(347, 'Wooden Desk Organizer', 'Elegant wooden organizer for stationery.', 'Office Supplies', 'Desk Organizer', 1499.99, NOW()),
(348, 'Colorful Binder Clips', 'Assorted binder clips for document organization.', 'Office Supplies', 'Binder Clips', 299.99, NOW()),
(349, 'Standing Desk Mat', 'Anti-fatigue mat for standing desks.', 'Furniture', 'Desk Mat', 2999.99, NOW()),
(350, 'Filing Cabinet with Locks', 'Secure filing cabinet for important documents.', 'Furniture', 'Filing Cabinet', 9999.99, NOW()),
(351, 'Royal Canin Dog Food', 'Nutritional food for adult dogs.', 'Pet Food', 'Dog Food', 2499.99, NOW()),
(352, 'Hill’s Science Diet Cat Food', 'Balanced nutrition for indoor cats.', 'Pet Food', 'Cat Food', 1999.99, NOW()),
(353, 'Purina Pro Plan Puppy Food', 'Specially formulated puppy food for growth.', 'Pet Food', 'Puppy Food', 2999.99, NOW()),
(354, 'Blue Buffalo Wilderness Dog Food', 'High protein dog food with real meat.', 'Pet Food', 'Dog Food', 3299.99, NOW()),
(355, 'Wellness CORE Grain-Free Cat Food', 'Grain-free formula for optimal health.', 'Pet Food', 'Cat Food', 2999.99, NOW()),
(356, 'Nutrish Zero Grain Dog Food', 'Zero grain recipe for sensitive stomachs.', 'Pet Food', 'Dog Food', 2499.99, NOW()),
(357, 'Fancy Feast Gourmet Cat Food', 'Delicious gourmet wet food for cats.', 'Pet Food', 'Wet Cat Food', 899.99, NOW()),
(358, 'Pedigree Adult Dog Food', 'Complete nutrition for adult dogs.', 'Pet Food', 'Dog Food', 1999.99, NOW()),
(359, 'Orijen Cat & Kitten Food', 'Biologically appropriate food for cats.', 'Pet Food', 'Cat Food', 3999.99, NOW()),
(360, 'Royal Canin Size Health Nutrition', 'Dog food formulated for specific sizes.', 'Pet Food', 'Dog Food', 2499.99, NOW()),
(361, 'Petstages Dogwood Stick', 'Durable chew toy that mimics real wood.', 'Toys', 'Dog Toy', 499.99, NOW()),
(362, 'KONG Classic Dog Toy', 'Durable rubber toy for stuffing treats.', 'Toys', 'Dog Toy', 899.99, NOW()),
(363, 'Nylabone DuraChew', 'Long-lasting chew for aggressive chewers.', 'Toys', 'Dog Toy', 499.99, NOW()),
(364, 'Tuffy’s Ultimate Ring Dog Toy', 'Super tough toy for rough play.', 'Toys', 'Dog Toy', 1299.99, NOW()),
(365, 'ZippyPaws Burrow Squeaky Toy', 'Interactive toy with hidden squeaky critters.', 'Toys', 'Dog Toy', 999.99, NOW()),
(366, 'Cat Dancer Cat Toy', 'Interactive toy that encourages play.', 'Toys', 'Cat Toy', 399.99, NOW()),
(367, 'PetSafe Fishbowl Cat Toy', 'Battery-operated toy that simulates fish movement.', 'Toys', 'Cat Toy', 1499.99, NOW()),
(368, 'Wand with Feather Cat Toy', 'Interactive wand toy with feathers.', 'Toys', 'Cat Toy', 599.99, NOW()),
(369, 'Catit Senses 2.0 Food Tree', 'Interactive feeder that stimulates cats.', 'Toys', 'Cat Toy', 1999.99, NOW()),
(370, 'PetSafe Automatic Ball Launcher', 'Fetch toy that launches balls automatically.', 'Toys', 'Dog Toy', 6999.99, NOW()),
(371, 'Hartz Chew Toy', 'Durable chew toy for dogs.', 'Toys', 'Dog Toy', 599.99, NOW()),
(372, 'Frisco Cat Scratching Post', 'Sturdy scratching post for cats.', 'Accessories', 'Scratching Post', 1299.99, NOW()),
(373, 'PetFusion Ultimate Dog Bed', 'Orthopedic bed for comfort.', 'Accessories', 'Dog Bed', 4999.99, NOW()),
(374, 'KONG Cat Wobbler', 'Interactive treat-dispensing toy for cats.', 'Toys', 'Cat Toy', 799.99, NOW()),
(375, 'Outward Hound Hide-A-Squirrel Toy', 'Plush puzzle toy for dogs.', 'Toys', 'Dog Toy', 1299.99, NOW()),
(376, 'PetSafe Healthy Pet Feeder', 'Automatic pet feeder with portion control.', 'Accessories', 'Feeder', 4999.99, NOW()),
(377, 'Dog Training Clicker', 'Clicker for training dogs effectively.', 'Accessories', 'Training Tool', 199.99, NOW()),
(378, 'Pet Grooming Brush', 'Double-sided brush for pets.', 'Accessories', 'Grooming Tool', 299.99, NOW()),
(379, 'Dog Collar with LED Light', 'Collar that lights up for safety.', 'Accessories', 'Collar', 799.99, NOW()),
(380, 'Cat Litter Box', 'Self-cleaning litter box for convenience.', 'Accessories', 'Litter Box', 8999.99, NOW()),
(381, 'Pet Water Fountain', 'Continuous water supply for pets.', 'Accessories', 'Water Fountain', 1999.99, NOW()),
(382, 'Portable Dog Water Bottle', 'On-the-go water bottle for dogs.', 'Accessories', 'Water Bottle', 499.99, NOW()),
(383, 'Adjustable Pet Harness', 'Comfortable harness for walks.', 'Accessories', 'Harness', 999.99, NOW()),
(384, 'Pet Carrier Backpack', 'Comfortable backpack carrier for small pets.', 'Accessories', 'Carrier', 2999.99, NOW()),
(385, 'Dog Life Jacket', 'Safety jacket for dogs during water activities.', 'Accessories', 'Life Jacket', 2499.99, NOW()),
(386, 'Cat Bed', 'Cozy bed for cats to snuggle.', 'Accessories', 'Cat Bed', 1499.99, NOW()),
(387, 'Dog Leash', 'Durable leash for walks and training.', 'Accessories', 'Leash', 599.99, NOW()),
(388, 'Pet First Aid Kit', 'Essential kit for pet emergencies.', 'Accessories', 'First Aid Kit', 999.99, NOW()),
(389, 'Squeaky Dog Toy', 'Soft toy that squeaks for extra fun.', 'Toys', 'Dog Toy', 399.99, NOW()),
(390, 'Litter Box Mat', 'Traps litter for a cleaner home.', 'Accessories', 'Litter Mat', 499.99, NOW()),
(391, 'Pet Cooling Mat', 'Keeps pets cool on hot days.', 'Accessories', 'Cooling Mat', 1999.99, NOW()),
(392, 'Catnip Toys', 'Cat toys filled with catnip for excitement.', 'Toys', 'Cat Toy', 299.99, NOW()),
(393, 'Pet Food Storage Container', 'Keeps pet food fresh and secure.', 'Accessories', 'Storage Container', 999.99, NOW()),
(394, 'Cat Scratching Pad', 'Sustainable scratching pad for cats.', 'Accessories', 'Scratching Pad', 699.99, NOW()),
(395, 'Dog Tie-Out Cable', 'Cable for outdoor dog restraint.', 'Accessories', 'Tie-Out', 599.99, NOW()),
(396, 'Cat Carrier', 'Easy-to-carry carrier for travel.', 'Accessories', 'Carrier', 2999.99, NOW()),
(397, 'Pet Travel Bowl', 'Collapsible bowl for food and water.', 'Accessories', 'Travel Bowl', 399.99, NOW()),
(398, 'Grooming Gloves', 'Gloves that remove pet hair while petting.', 'Accessories', 'Grooming Tool', 499.99, NOW()),
(399, 'Pet Bowls Set', 'Durable food and water bowls for pets.', 'Accessories', 'Bowls', 799.99, NOW()),
(400, 'Interactive Cat Laser Toy', 'Laser toy for hours of play.', 'Toys', 'Cat Toy', 999.99, NOW()),
(401, 'Sofa Set', 'Luxury leather sofa set for living room.', 'Furniture', 'Sofa', 29999.99, NOW()),
(402, 'Dining Table', 'Wooden dining table with seating for six.', 'Furniture', 'Table', 19999.99, NOW()),
(403, 'Office Chair', 'Ergonomic chair for long hours of work.', 'Furniture', 'Chair', 7999.99, NOW()),
(404, 'Bookshelf', 'Stylish bookshelf for storing books and decor.', 'Furniture', 'Bookshelf', 6999.99, NOW()),
(405, 'Coffee Table', 'Modern coffee table with glass top.', 'Furniture', 'Table', 4999.99, NOW()),
(406, 'Bed Frame', 'Queen-size bed frame with headboard.', 'Furniture', 'Bed', 14999.99, NOW()),
(407, 'Wardrobe', 'Spacious wardrobe with sliding doors.', 'Furniture', 'Wardrobe', 24999.99, NOW()),
(408, 'Accent Chair', 'Stylish accent chair for any room.', 'Furniture', 'Chair', 4999.99, NOW()),
(409, 'Outdoor Patio Set', 'Weather-resistant patio furniture set.', 'Furniture', 'Outdoor Set', 19999.99, NOW()),
(410, 'Area Rug', 'Soft area rug to enhance living space.', 'Home Decor', 'Rug', 2999.99, NOW()),
(411, 'Wall Art', 'Framed artwork to beautify walls.', 'Home Decor', 'Art', 2499.99, NOW()),
(412, 'Table Lamp', 'Elegant lamp for accent lighting.', 'Home Decor', 'Lamp', 1499.99, NOW()),
(413, 'Curtains', 'Heavy drapes for privacy and style.', 'Home Decor', 'Curtains', 1999.99, NOW()),
(414, 'Mirror', 'Full-length mirror for dressing rooms.', 'Home Decor', 'Mirror', 3499.99, NOW()),
(415, 'Indoor Plant', 'Low-maintenance indoor plant for decor.', 'Home Decor', 'Plant', 799.99, NOW()),
(416, 'Cushion Covers', 'Decorative cushion covers for sofas.', 'Home Decor', 'Cushion Cover', 999.99, NOW()),
(417, 'Flower Vase', 'Elegant vase for displaying flowers.', 'Home Decor', 'Vase', 1299.99, NOW()),
(418, 'Wall Clock', 'Modern wall clock for timekeeping.', 'Home Decor', 'Clock', 1999.99, NOW()),
(419, 'Candles Set', 'Scented candles for ambiance.', 'Home Decor', 'Candles', 899.99, NOW()),
(420, 'Garden Shovel', 'Durable shovel for gardening tasks.', 'Gardening Tools', 'Shovel', 499.99, NOW()),
(421, 'Hand Trowel', 'Essential tool for planting and digging.', 'Gardening Tools', 'Trowel', 299.99, NOW()),
(422, 'Pruning Shears', 'High-quality shears for trimming plants.', 'Gardening Tools', 'Shears', 899.99, NOW()),
(423, 'Garden Rake', 'Metal rake for leveling soil and clearing debris.', 'Gardening Tools', 'Rake', 699.99, NOW()),
(424, 'Watering Can', 'Lightweight watering can for easy use.', 'Gardening Tools', 'Watering Can', 499.99, NOW()),
(425, 'Garden Hose', 'Flexible hose for watering plants.', 'Gardening Tools', 'Hose', 1299.99, NOW()),
(426, 'Plant Pots Set', 'Decorative pots for indoor and outdoor plants.', 'Gardening Tools', 'Pots', 999.99, NOW()),
(427, 'Compost Bin', 'Bin for composting kitchen and garden waste.', 'Gardening Tools', 'Compost Bin', 2499.99, NOW()),
(428, 'Garden Gloves', 'Durable gloves for gardening protection.', 'Gardening Tools', 'Gloves', 299.99, NOW()),
(429, 'Fertilizer Spreader', 'Spreader for evenly distributing fertilizer.', 'Gardening Tools', 'Spreader', 1499.99, NOW()),
(430, 'Cutting Board', 'Bamboo cutting board for kitchen use.', 'Kitchenware', 'Cutting Board', 799.99, NOW()),
(431, 'Cookware Set', 'Non-stick cookware set for home cooking.', 'Kitchenware', 'Cookware', 4999.99, NOW()),
(432, 'Blender', 'High-speed blender for smoothies and sauces.', 'Kitchenware', 'Blender', 2999.99, NOW()),
(433, 'Dinner Set', 'Elegant dinner set for family meals.', 'Kitchenware', 'Dinnerware', 3999.99, NOW()),
(434, 'Measuring Cups', 'Set of measuring cups for accurate cooking.', 'Kitchenware', 'Measuring Tools', 499.99, NOW()),
(435, 'Spice Rack', 'Rotating spice rack with jars.', 'Kitchenware', 'Spice Rack', 1299.99, NOW()),
(436, 'Food Storage Containers', 'Set of airtight containers for food.', 'Kitchenware', 'Storage Containers', 999.99, NOW()),
(437, 'Oven Mitts', 'Heat-resistant mitts for cooking safety.', 'Kitchenware', 'Oven Mitts', 299.99, NOW()),
(438, 'Cutlery Set', 'Stainless steel cutlery for dining.', 'Kitchenware', 'Cutlery', 1999.99, NOW()),
(439, 'Coffee Maker', 'Brew coffee easily at home.', 'Kitchenware', 'Coffee Maker', 2999.99, NOW()),
(440, 'Smartwatch', 'Fitness tracking smartwatch with notifications.', 'Wearable Tech', 'Smartwatch', 19999.99, NOW()),
(441, 'Fitness Tracker', 'Activity tracker with heart rate monitor.', 'Wearable Tech', 'Fitness Tracker', 9999.99, NOW()),
(442, 'Bluetooth Headphones', 'Wireless headphones with noise cancellation.', 'Wearable Tech', 'Headphones', 7999.99, NOW()),
(443, 'Smart Glasses', 'Augmented reality glasses for smart use.', 'Wearable Tech', 'Smart Glasses', 29999.99, NOW()),
(444, 'VR Headset', 'Virtual reality headset for immersive experiences.', 'Wearable Tech', 'VR Headset', 24999.99, NOW()),
(445, 'Smart Ring', 'Wearable technology for tracking health metrics.', 'Wearable Tech', 'Smart Ring', 5999.99, NOW()),
(446, 'Health Monitor Band', 'Band that tracks vital signs and activity.', 'Wearable Tech', 'Health Monitor', 3999.99, NOW()),
(447, 'Sleep Tracking Mask', 'Mask that tracks sleep patterns.', 'Wearable Tech', 'Sleep Mask', 2999.99, NOW()),
(448, 'Portable Charger', 'High-capacity power bank for devices.', 'Wearable Tech', 'Charger', 1999.99, NOW()),
(449, 'Robot Vacuum', 'Automatic vacuum cleaner for home.', 'Home Appliances', 'Vacuum', 14999.99, NOW()),
(450, 'Air Fryer', 'Healthier frying alternative for cooking.', 'Home Appliances', 'Air Fryer', 9999.99, NOW()),
(451, 'Microwave Oven', 'Compact microwave for quick meals.', 'Home Appliances', 'Microwave', 6999.99, NOW()),
(452, 'Refrigerator', 'Energy-efficient refrigerator with large capacity.', 'Home Appliances', 'Refrigerator', 29999.99, NOW()),
(453, 'Washing Machine', 'Top-load washing machine for efficient laundry.', 'Home Appliances', 'Washing Machine', 19999.99, NOW()),
(454, 'Electric Kettle', 'Fast boiling kettle for tea and coffee.', 'Home Appliances', 'Kettle', 2499.99, NOW()),
(455, 'Dishwasher', 'Automatic dishwasher for easy cleaning.', 'Home Appliances', 'Dishwasher', 29999.99, NOW()),
(456, 'Induction Cooktop', 'Portable induction cooktop for cooking.', 'Home Appliances', 'Cooktop', 4999.99, NOW()),
(457, 'Steam Iron', 'Powerful iron for wrinkle-free clothes.', 'Home Appliances', 'Iron', 1999.99, NOW()),
(458, 'Blender with Grinder', 'Multi-functional blender with grinding feature.', 'Home Appliances', 'Blender', 3999.99, NOW()),
(459, 'Smartphone Holder', 'Adjustable holder for smartphones.', 'Accessories', 'Phone Holder', 799.99, NOW()),
(460, 'Screen Protector', 'Tempered glass screen protector for phones.', 'Accessories', 'Screen Protector', 499.99, NOW()),
(461, 'Wireless Charger', 'Fast wireless charging pad for smartphones.', 'Accessories', 'Charger', 1499.99, NOW()),
(462, 'Phone Case', 'Stylish and protective phone case.', 'Accessories', 'Phone Case', 999.99, NOW()),
(463, 'Bluetooth Speaker', 'Portable speaker with high-quality sound.', 'Accessories', 'Speaker', 2999.99, NOW()),
(464, 'Power Bank', 'Compact power bank for charging devices on the go.', 'Accessories', 'Power Bank', 1499.99, NOW()),
(465, 'Car Mount for Smartphones', 'Secure mount for smartphones in cars.', 'Accessories', 'Car Mount', 799.99, NOW()),
(466, 'Fitness Armband', 'Adjustable armband for smartphones during workouts.', 'Accessories', 'Armband', 899.99, NOW()),
(467, 'Stylus Pen', 'Precision stylus for touchscreen devices.', 'Accessories', 'Stylus', 299.99, NOW()),
(468, 'Smartphone Tripod', 'Adjustable tripod for smartphone photography.', 'Accessories', 'Tripod', 1499.99, NOW()),
(469, 'Selfie Stick', 'Extendable selfie stick for group photos.', 'Accessories', 'Selfie Stick', 599.99, NOW()),
(470, 'Phone Cleaning Kit', 'Complete kit for cleaning smartphones.', 'Accessories', 'Cleaning Kit', 499.99, NOW()),
(471, 'Recliner Chair', 'Comfortable recliner for relaxing.', 'Furniture', 'Chair', 15999.99, NOW()),
(472, 'Dining Chair', 'Set of four dining chairs.', 'Furniture', 'Chair', 8999.99, NOW()),
(473, 'Coffee Machine', 'Espresso machine for home brewing.', 'Kitchenware', 'Coffee Machine', 14999.99, NOW()),
(474, 'Electric Can Opener', 'Automatic can opener for convenience.', 'Kitchenware', 'Can Opener', 1999.99, NOW()),
(475, 'Kitchen Knife Set', 'Professional knives for kitchen prep.', 'Kitchenware', 'Knives', 3999.99, NOW()),
(476, 'Pots and Pans Set', 'Durable pots and pans for various cooking needs.', 'Kitchenware', 'Cookware', 5999.99, NOW()),
(477, 'Salad Spinner', 'Easy-to-use salad spinner for fresh greens.', 'Kitchenware', 'Spinner', 899.99, NOW()),
(478, 'Food Processor', 'Multi-functional food processor for easy cooking.', 'Kitchenware', 'Food Processor', 7999.99, NOW()),
(479, 'Smart LED Light Bulb', 'Wi-Fi enabled smart light bulb.', 'Home Appliances', 'Lighting', 999.99, NOW()),
(480, 'Air Purifier', 'Removes allergens and pollutants from the air.', 'Home Appliances', 'Air Purifier', 8999.99, NOW()),
(481, 'Dehumidifier', 'Compact dehumidifier for moisture control.', 'Home Appliances', 'Dehumidifier', 6999.99, NOW()),
(482, 'Smart Refrigerator', 'Refrigerator with smart features and connectivity.', 'Home Appliances', 'Refrigerator', 49999.99, NOW()),
(483, 'Smart Oven', 'Oven with app control and smart features.', 'Home Appliances', 'Oven', 39999.99, NOW()),
(484, 'Pressure Cooker', 'Electric pressure cooker for fast cooking.', 'Home Appliances', 'Cooker', 4999.99, NOW()),
(485, 'Portable Air Conditioner', 'Compact air conditioner for small spaces.', 'Home Appliances', 'Air Conditioner', 24999.99, NOW()),
(486, 'Electric Grill', 'Indoor electric grill for BBQ at home.', 'Home Appliances', 'Grill', 5999.99, NOW()),
(487, 'Digital Thermometer', 'Instant-read thermometer for cooking.', 'Kitchenware', 'Thermometer', 499.99, NOW()),
(488, 'Bamboo Drawer Organizers', 'Eco-friendly organizers for kitchen drawers.', 'Kitchenware', 'Organizer', 1299.99, NOW()),
(489, 'Wall Shelf', 'Floating shelf for displaying decor.', 'Home Decor', 'Shelf', 1499.99, NOW()),
(490, 'Artificial Plant', 'Realistic artificial plant for low maintenance decor.', 'Home Decor', 'Plant', 899.99, NOW()),
(491, 'Photo Frame Set', 'Set of decorative photo frames.', 'Home Decor', 'Frame', 1999.99, NOW()),
(492, 'Garden Hose Reel', 'Retractable hose reel for easy storage.', 'Gardening Tools', 'Hose Reel', 1999.99, NOW()),
(493, 'Garden Shears', 'Heavy-duty shears for trimming bushes.', 'Gardening Tools', 'Shears', 1299.99, NOW()),
(494, 'Plant Watering Spike', 'Automatic watering spike for potted plants.', 'Gardening Tools', 'Watering Spike', 599.99, NOW()),
(495, 'Garden Kneeler', 'Foldable kneeler for comfortable gardening.', 'Gardening Tools', 'Kneeler', 1299.99, NOW()),
(496, 'Smartphone Gimbal Stabilizer', 'Gimbal for stable smartphone video recording.', 'Wearable Tech', 'Gimbal', 9999.99, NOW()),
(497, 'Wireless Earbuds', 'True wireless earbuds with touch controls.', 'Wearable Tech', 'Earbuds', 6999.99, NOW()),
(498, 'Fitness Smartwatch', 'Smartwatch with built-in fitness tracker.', 'Wearable Tech', 'Smartwatch', 14999.99, NOW()),
(499, 'Smart Scale', 'Digital scale that syncs with health apps.', 'Wearable Tech', 'Scale', 2999.99, NOW()),
(500, 'Virtual Reality Gloves', 'Gloves for an immersive VR experience.', 'Wearable Tech', 'VR Gloves', 19999.99, NOW());



