INSERT INTO store.product_rating_review (product_id, product_rating, product_review)
VALUES
(21, 4.5, 'Great mouse for long hours of use, very comfortable.'),
(22, 4.8, 'Best mechanical keyboard I’ve used, love the RGB lighting.'),
(23, 4.6, 'Reliable portable charger, holds a charge well.'),
(24, 4.2, 'Very useful for connecting multiple devices, highly recommend.'),
(25, 4.7, 'Excellent webcam for video calls, very clear picture.'),
(26, 4.5, 'Perfect for gaming, great precision and comfort.'),
(27, 4.9, 'Top-notch keyboard for gamers, amazing build quality.'),
(28, 4.7, 'Fast data transfer and very portable, love it.'),
(29, 4.6, 'Nice design and very responsive, worth the price.'),
(30, 4.8, 'Powerful laptop with great battery life, perfect for work.'),
(31, 4.7, 'Amazing display quality, great for graphic design.'),
(32, 4.9, 'Exceptional performance, ideal for serious gamers.'),
(33, 4.8, 'Fantastic sound quality for streaming, very easy to use.'),
(34, 4.5, 'Great for esports, responsive keys and solid feel.'),
(35, 4.6, 'Comfortable and high-quality sound, love these headphones.'),
(36, 4.9, 'Perfect for digital artists, very precise and easy to use.'),
(37, 4.5, 'Very useful for multiple connections, solid build.'),
(38, 4.7, 'Excellent speed for gaming, very reliable.'),
(39, 4.6, 'Great sound quality and comfort for long gaming sessions.'),
(40, 4.8, 'Fast and reliable router, excellent coverage.'),
(41, 4.7, 'Amazing VR experience, very immersive.'),
(42, 4.5, 'Great smart speaker, easy to use with Alexa.'),
(43, 4.6, 'Good value for a dual band router, solid performance.'),
(44, 4.8, 'Excellent sound quality, very comfortable to wear.'),
(45, 4.7, 'Perfect for reading, great battery life.'),
(46, 4.6, 'Customizable weights are a game changer, very comfortable.'),
(47, 4.5, 'Good sound quality and comfortable for long hours.'),
(48, 4.9, 'Versatile tablet, perfect for both work and play.'),
(49, 4.8, 'Amazing performance for creatives, highly recommend.'),
(50, 4.9, 'Outstanding graphics, a must-have for gamers.'),
(51, 4.8, 'Incredible noise cancellation, very comfortable.'),
(52, 4.6, 'Perfect for streamers, customizable and easy to use.'),
(53, 4.9, 'Love the low-profile design, perfect for gaming.'),
(54, 4.7, 'Great entry-level DSLR, very user-friendly.'),
(55, 4.8, 'Excellent for action shots, very durable.'),
(56, 4.9, 'Best graphics card on the market, unbeatable performance.'),
(57, 4.8, 'Amazing CPU for gaming, very powerful.'),
(58, 4.6, 'Great RAM for gaming, very reliable.'),
(59, 4.5, 'Good storage solution, easy to use.'),
(60, 4.8, 'Fantastic monitor for productivity, great colors.'),
(61, 4.7, 'Powerful sound in a portable speaker, love it.'),
(62, 4.5, 'Durable and reliable, worth the price.'),
(63, 4.9, 'Best keyboard for gaming, very responsive.'),
(64, 4.7, 'Excellent health tracking features, very stylish.'),
(65, 4.8, 'Great compact drone, easy to use and control.'),
(66, 4.5, 'Solid keyboard for gaming, good value.'),
(67, 4.6, 'Lightweight and very comfortable for long sessions.'),
(68, 4.9, 'Powerful tablet, perfect for professionals.'),
(69, 4.8, 'Incredible color accuracy, perfect for designers.'),
(70, 4.9, 'Best noise-cancelling headphones I’ve owned.'),
(71, 4.6, 'Good sound quality, very comfortable for gaming.'),
(72, 4.8, 'Stunning visuals and very powerful, love it.'),
(73, 4.9, 'Incredible monitor for professionals, very high quality.'),
(74, 4.6, 'Great for streaming, easy to set up.'),
(75, 4.5, 'Excellent airflow, very spacious.'),
(76, 4.8, 'Great mesh system, easy to install and manage.'),
(77, 4.7, 'Very good color accuracy, worth the investment.'),
(78, 4.6, 'Great sound system, very powerful.'),
(79, 4.4, 'Lightweight and decent sound for the price.'),
(80, 4.7, 'Good battery life and sound quality.'),
(81, 4.5, 'Very efficient, quick boiling.'),
(82, 4.6, 'Great performance for the price, very useful.'),
(83, 4.8, 'Very powerful, easy to use.'),
(84, 4.7, 'Quiet and efficient, love the remote control.'),
(85, 4.6, 'Good precision and easy to use.'),
(86, 4.5, 'Durable and functional, great for serving.'),
(87, 4.8, 'Excellent non-stick performance, very durable.'),
(88, 4.7, 'Very convenient for food storage, love it.'),
(89, 4.9, 'Incredible water purification, highly effective.'),
(90, 4.6, 'Very bright and efficient, long-lasting.'),
(91, 4.7, 'Quick meals, very easy to use.'),
(92, 4.5, 'Good protection for my appliances, very reliable.'),
(93, 4.8, 'Fantastic washing machine, very efficient.'),
(94, 4.6, 'Great microwave, love the grilling feature.'),
(95, 4.5, 'Very convenient for mixing, good quality.'),
(96, 4.7, 'Sturdy and well-organized, perfect for tools.'),
(97, 4.6, 'Great rice cooker, very smart features.'),
(98, 4.8, 'Very effective cooling, energy efficient.'),
(99, 4.5, 'Good features for the price, reliable smartphone.'),
(100, 4.8, 'Great grip and comfort for yoga enthusiasts.'),
(101, 4.5, 'Great fan with a sleek design and silent operation.'),
(102, 4.0, 'Effective trimmer, easy to use.'),
(103, 4.7, 'Reliable UPS, never faced a power issue.'),
(104, 4.2, 'Elegant serving set, perfect for dinners.'),
(105, 4.8, 'Excellent induction cooktop, heats quickly.'),
(106, 4.5, 'Compact and efficient water purifier.'),
(107, 4.9, 'Amazing picture quality, worth the price!'),
(108, 4.3, 'Good exhaust fan, does the job well.'),
(109, 4.6, 'Rich sound quality, highly portable.'),
(110, 4.1, 'Good facial kit, leaves skin glowing.'),
(111, 4.4, 'Instant heating, very satisfied.'),
(112, 4.0, 'Spacious and durable sports bag.'),
(113, 4.7, 'Great RO technology, water tastes better.'),
(114, 4.5, 'Stylish smartwatch, great features.'),
(115, 4.8, 'Powerful pressure washer, cleans effectively.'),
(116, 4.2, 'Great storage solution for the kitchen.'),
(117, 4.6, 'Excellent home theater system, immersive sound.'),
(118, 4.3, 'Fast cooking, very reliable.'),
(119, 4.4, 'Quiet and efficient ceiling fan.'),
(120, 4.5, 'Heats up quickly, great styling tool.'),
(121, 4.3, 'Good electric tandoor, easy to use.'),
(122, 4.6, 'Convenient hot and cold water dispenser.'),
(123, 4.5, 'Curls beautifully, easy to handle.'),
(124, 4.0, 'Smart plug works as expected.'),
(125, 4.2, 'Color-changing lights, perfect for parties.'),
(126, 4.1, 'Reliable set-top box, good channel selection.'),
(127, 4.4, 'Easy to set up and use smart plug.'),
(128, 4.5, 'Leaves skin soft and fragrant.'),
(129, 4.6, 'Very comfortable for running.'),
(130, 4.2, 'Perfect for gym, spacious and durable.'),
(131, 4.5, 'Versatile and efficient food processor.'),
(132, 4.3, 'Good picture quality for the price.'),
(133, 4.0, 'Stylish lamp, adds to the decor.'),
(134, 4.9, 'Best gaming console on the market!'),
(135, 4.3, 'Heats the room quickly, very effective.'),
(136, 4.4, 'Good sound quality, easy to use.'),
(137, 4.5, 'Air quality improved significantly.'),
(138, 4.6, 'Great hair dryer, multiple settings help.'),
(139, 4.2, 'Smart bulb with good connectivity.'),
(140, 4.1, 'Stylish and functional, love it!'),
(141, 4.7, 'Excellent sound quality for wireless earbuds.'),
(142, 4.0, 'Durable football, great for outdoor play.'),
(143, 4.5, 'Trendy and protective sunglasses.'),
(144, 4.1, 'Nourishes hair well, happy with the results.'),
(145, 4.6, 'Works perfectly for my computer needs.'),
(146, 4.4, 'Compact and efficient for travel.'),
(147, 4.3, 'Powerful and effective mixer grinder.'),
(148, 4.0, 'Good quality mixing bowl, easy to clean.'),
(149, 4.7, 'Excellent cooling and heating performance.'),
(150, 4.5, 'Reliable and convenient for travel.'),
(151, 4.8, 'Great battery life and performance.'),
(152, 4.3, 'Bright lights, improve visibility significantly.'),
(153, 4.4, 'Engine runs smoother with this oil.'),
(154, 4.6, 'Reliable tyres, great grip.'),
(155, 4.2, 'Essential for vehicle safety, good quality.'),
(156, 4.1, 'Great coolant, engine stays cool.'),
(157, 4.5, 'Comprehensive tool kit for all needs.'),
(158, 4.0, 'Bright lights, improve night driving.'),
(159, 4.4, 'Durable cover, protects well.'),
(160, 4.6, 'Effective brake pads, reliable stopping power.'),
(161, 4.3, 'Adds shine and protection to the car.'),
(162, 4.5, 'Very handy for car interiors.'),
(163, 4.1, 'Useful for emergency situations.'),
(164, 4.6, 'Sound quality is amazing for car speakers.'),
(165, 4.2, 'Sturdy ramps, very reliable.'),
(166, 4.5, 'Keeps the car organized, highly functional.'),
(167, 4.3, 'Good LED lights for interiors.'),
(168, 4.8, 'Excellent for safer parking.'),
(169, 4.1, 'Convenient phone holder, very stable.'),
(170, 4.6, 'Improved engine efficiency noticed.'),
(171, 4.7, 'Effective radar detection, good buy.'),
(172, 4.0, 'Good protectant for dashboard.'),
(173, 4.5, 'Great sound, easy to install.'),
(174, 4.6, 'High grip tyres, very satisfied.'),
(175, 4.2, 'Quick wax, easy to apply.'),
(176, 4.5, 'Very sturdy and well-organized.'),
(177, 4.4, 'Handy for emergencies, very useful.'),
(178, 4.6, 'Solid hitch, durable and reliable.'),
(179, 4.5, 'Everything needed for a good wash.'),
(180, 4.1, 'Protects well from UV rays.'),
(181, 4.4, 'Durable wiper blades, clear visibility.'),
(182, 4.3, 'Very bright and useful for repairs.'),
(183, 4.5, 'Cleans well, easy to use.'),
(184, 4.8, 'Powerful winch, very effective for off-road.'),
(185, 4.2, 'Smooth finish with this clay bar.'),
(186, 4.3, 'Sturdy flares, great for off-road vehicles.'),
(187, 4.6, 'Powerful and effective for projects.'),
(188, 4.5, 'Good quality and fit for trucks.'),
(189, 4.4, 'Heavy-duty and protects the vehicle well.'),
(190, 4.5, 'Excellent for extra storage needs.'),
(191, 4.6, 'Charges quickly, very effective.'),
(192, 4.7, 'Protects well, durable design.'),
(193, 4.5, 'High performance, very reliable.'),
(194, 4.6, 'Bright lights for night adventures.'),
(195, 4.4, 'Very sturdy and reliable for towing.'),
(196, 4.5, 'Strong and well-built for off-road vehicles.'),
(197, 4.3, 'Good for hands-free calls, easy setup.'),
(198, 4.6, 'Enhances sound quality significantly.'),
(199, 4.4, 'Reduces wear, good product.'),
(200, 4.5, 'Very useful for securing loads.'),
(201, 5, 'A beautifully written tale about following your dreams.'),
(202, 4, 'An insightful overview of humanity’s history.'),
(203, 5, 'An inspiring memoir that resonates deeply.'),
(204, 4, 'Very practical advice on changing habits.'),
(205, 4, 'A gripping psychological thriller with a twist.'),
(206, 5, 'Simple yet profound guide to building better habits.'),
(207, 5, 'A powerful memoir that highlights resilience.'),
(208, 5, 'Timeless classic that captures the essence of the era.'),
(209, 5, 'Magical and adventurous, perfect for all ages.'),
(210, 4, 'Captures teenage struggles with authenticity.'),
(211, 4, 'A dark, twisted narrative that keeps you guessing.'),
(212, 5, 'A chilling look at totalitarianism that feels relevant today.'),
(213, 5, 'A romantic classic that never gets old.'),
(214, 5, 'A poignant and moving story of a young girl in hiding.'),
(215, 4, 'A refreshingly honest self-help book.'),
(216, 5, 'A delightful adventure in a richly imagined world.'),
(217, 5, 'A profound story that touches the heart.'),
(218, 4, 'A beautiful exploration of love and loss.'),
(219, 5, 'Fascinating insights into the universe.'),
(220, 5, 'Timeless wisdom on strategy and warfare.'),
(221, 5, 'A unique and heartbreaking perspective on war.'),
(222, 4, 'A compelling true story about ethics in medicine.'),
(223, 5, 'A masterful thriller that kept me on the edge of my seat.'),
(224, 5, 'A complex and captivating science fiction epic.'),
(225, 5, 'An engaging story about survival and rebellion.'),
(226, 4, 'Beautifully written with a deep emotional core.'),
(227, 4, 'A fascinating fantasy journey worth exploring.'),
(228, 5, 'Practical and transformative advice for personal growth.'),
(229, 5, 'An essential read that captures the human experience.'),
(230, 5, 'A moving tale of friendship and redemption.'),
(231, 5, 'A gripping and beautifully told story.'),
(232, 5, 'A haunting tale that stays with you long after reading.'),
(233, 5, 'A mesmerizing fantasy that captivates the imagination.'),
(234, 4, 'A thoughtful exploration of family dynamics.'),
(235, 4, 'A tender and realistic portrayal of relationships.'),
(236, 5, 'A beautifully woven retelling of a classic tale.'),
(237, 4, 'A thought-provoking exploration of identity.'),
(238, 4, 'A humorous yet touching take on life’s absurdities.'),
(239, 5, 'A creative exploration of life’s choices and regrets.'),
(240, 5, 'An engaging and entertaining read about family.'),
(241, 5, 'A deeply psychological thriller with strong characters.'),
(242, 5, 'A suspenseful and unpredictable mystery.'),
(243, 5, 'A heartwarming journey of self-discovery.'),
(244, 4, 'An intriguing psychological thriller.'),
(245, 4, 'A unique concept with an engaging narrative.'),
(246, 5, 'A beautifully written post-apocalyptic tale.'),
(247, 5, 'An enthralling look at fame and its consequences.'),
(248, 5, 'A touching story about connection and loss.'),
(249, 4, 'A compelling love story with deep emotional impact.'),
(250, 5, 'A powerful narrative set against a tragic backdrop.'),
(251, 4, 'Sturdy and reliable for organizing documents.'),
(252, 5, 'Smooth and comfortable writing experience.'),
(253, 5, 'Great for quick notes and reminders.'),
(254, 4, 'Very durable and efficient for heavy tasks.'),
(255, 5, 'Perfect for writing and drawing with precision.'),
(256, 4, 'Great quality notebook with useful pockets.'),
(257, 5, 'Excellent quality for professional documents.'),
(258, 5, 'The best shredder for secure document disposal.'),
(259, 4, 'Convenient and functional tape dispenser.'),
(260, 5, 'Powerful and effective for multiple documents.'),
(261, 4, 'Great pencils for everyday writing.'),
(262, 5, 'Fun colors and washes out easily.'),
(263, 5, 'Luxury quality for serious note-takers.'),
(264, 4, 'Keeps your desk organized and tidy.'),
(265, 5, 'Excellent for creating neat labels.'),
(266, 4, 'Easy to use and very practical.'),
(267, 5, 'Perfect for arts and crafts projects.'),
(268, 4, 'Durable protectors for important documents.'),
(269, 5, 'Perfect for office organization and storage.'),
(270, 5, 'Super comfortable and adjustable.'),
(271, 5, 'Very spacious and ideal for home offices.'),
(272, 5, 'Great for alternating between sitting and standing.'),
(273, 5, 'Perfect size for meetings and discussions.'),
(274, 4, 'Stylish and functional for small spaces.'),
(275, 4, 'Good storage solution for office supplies.'),
(276, 5, 'Very comfortable with great support.'),
(277, 5, 'Sleek design perfect for modern offices.'),
(278, 4, 'Versatile and easy to transport.'),
(279, 4, 'Great for organizing items at home or office.'),
(280, 5, 'Very comfortable for long hours of work.'),
(281, 5, 'Fun colors and effective organization solution.'),
(282, 5, 'Great for permanent labeling.'),
(283, 5, 'Quality notebook for serious writers.'),
(284, 4, 'Great for keeping reports organized.'),
(285, 5, 'High quality and very useful for presentations.'),
(286, 5, 'Reliable and versatile for everyday use.'),
(287, 4, 'Keeps documents organized and tidy.'),
(288, 4, 'Stylish and functional for managing time.'),
(289, 5, 'Very smooth and enjoyable to write with.'),
(290, 4, 'Useful for pinning notes and reminders.'),
(291, 5, 'Very secure and reliable for document storage.'),
(292, 5, 'Perfect for modern home office setups.'),
(293, 5, 'Comfortable and perfect for long hours of work.'),
(294, 5, 'Great for shipping and mailing needs.'),
(295, 4, 'Efficient and easy to use for stapling.'),
(296, 4, 'Elegant design adds sophistication to the desk.'),
(297, 5, 'Extra sticky and very useful for various tasks.'),
(298, 4, 'Helps improve posture while working.'),
(299, 4, 'Good quality for the price.'),
(300, 5, 'Versatile and effective for various crafting needs.'),
(301, 4.5, 'Great for keeping my office organized!'),
(302, 4.8, 'High-quality toner with excellent print results.'),
(303, 4.2, 'Sturdy and durable, perfect for my documents.'),
(304, 4.7, 'Vibrant colors and smooth writing on whiteboards.'),
(305, 4.6, 'Spacious and stylish, perfect for my home office.'),
(306, 4.3, 'Bright light and adjustable, a must-have!'),
(307, 4.5, 'Helps me keep my desk tidy and organized.'),
(308, 4.1, 'Good quality gloves for medical use.'),
(309, 4.0, 'Convenient hooks for hanging items without damage.'),
(310, 4.4, 'Lightweight and easy to store when not in use.'),
(311, 4.3, 'Simple yet effective for protecting my desk.'),
(312, 4.5, 'Cleans my screens perfectly, very satisfied.'),
(313, 4.6, 'Great for sorting papers, very useful.'),
(314, 4.8, 'Comfortable and adjustable, perfect for long hours.'),
(315, 4.5, 'Very comfortable for typing, love it!'),
(316, 4.2, 'Sturdy bins that hold a lot of supplies.'),
(317, 4.1, 'Handy for quick notes, great quality.'),
(318, 4.4, 'Perfect height for my printer, very functional.'),
(319, 4.0, 'Great size for scheduling, good quality.'),
(320, 4.3, 'Classic design and keeps perfect time.'),
(321, 4.5, 'Perfect for my watercolor projects, very good quality.'),
(322, 4.2, 'Great for organizing important documents.'),
(323, 4.6, 'Protects my desk and looks nice too.'),
(324, 4.7, 'Adds style to my office, very functional.'),
(325, 4.5, 'Comfortable and supportive for meetings.'),
(326, 4.3, 'Effective in keeping my cables tidy.'),
(327, 4.4, 'Eco-friendly and writes smoothly, great choice.'),
(328, 4.2, 'Does the job, works well on whiteboards.'),
(329, 4.5, 'Very secure, I feel safe storing my valuables.'),
(330, 4.6, 'Perfect for our large meetings, spacious.'),
(331, 4.4, 'Very comfortable, great for long hours of work.'),
(332, 4.3, 'Compact and very useful for filing documents.'),
(333, 4.1, 'Good quality for crafting and printing.'),
(334, 4.5, 'Reliable printer paper, no jams so far.'),
(335, 4.7, 'A beautiful and spacious desk, very happy!'),
(336, 4.6, 'Holds a lot of files and looks great.'),
(337, 4.8, 'Love the mobility, great for presentations!'),
(338, 4.4, 'Great adhesive and works well for crafts.'),
(339, 4.3, 'Useful for keeping track of daily tasks.'),
(340, 4.5, 'Looks elegant and organizes well.'),
(341, 4.4, 'Heats water quickly, very convenient.'),
(342, 4.0, 'Handy for managing cords, good quality.'),
(343, 4.5, 'Write well and easy to erase, love them!'),
(344, 4.6, 'Sturdy and stylish, fits perfectly in my room.'),
(345, 4.2, 'Very helpful for keeping cool while working.'),
(346, 4.1, 'Perfect fit for my laptop, protects well.'),
(347, 4.4, 'Beautifully made and holds my supplies neatly.'),
(348, 4.5, 'Colorful and functional, a great buy!'),
(349, 4.3, 'Comfortable to stand on, very useful for my desk.'),
(350, 4.5, 'Excellent for secure document storage.'),
(351, 4.8, 'My dog loves it, very nutritious!'),
(352, 4.6, 'Great for indoor cats, they love it!'),
(353, 4.7, 'My puppy enjoys it and is growing well!'),
(354, 4.5, 'High protein and my dog loves it!'),
(355, 4.4, 'Great for my cat’s health, they love it!'),
(356, 4.2, 'My dog with a sensitive stomach does well on this.'),
(357, 4.6, 'My cat loves it, very high-quality food.'),
(358, 4.5, 'Good nutrition for my adult dog.'),
(359, 4.8, 'Best food for my cat, highly recommend!'),
(360, 4.4, 'Great for different dog sizes, my dog loves it!'),
(361, 4.3, 'Durable and my dog enjoys it!'),
(362, 4.5, 'My dog loves playing with this, great toy!'),
(363, 4.6, 'Lasts long and my dog loves it!'),
(364, 4.7, 'Super durable, great for rough play!'),
(365, 4.5, 'My dog enjoys finding the squeaky toys, fun!'),
(366, 4.8, 'Keeps my cat engaged, they love it!'),
(367, 4.4, 'Fun toy that my cat loves to chase!'),
(368, 4.6, 'Great for interactive play, very engaging!'),
(369, 4.5, 'Stimulates my cat’s mind, very effective!'),
(370, 4.7, 'Awesome toy for fetch, my dog loves it!'),
(371, 4.2, 'Durable and lasts long, my dog enjoys it!'),
(372, 4.5, 'Sturdy and perfect for my cat’s scratching needs.'),
(373, 4.8, 'My dog loves this bed, very comfortable!'),
(374, 4.6, 'Interactive and my cat enjoys it!'),
(375, 4.5, 'Cute puzzle toy, my dog loves it!'),
(376, 4.4, 'Very convenient for feeding my pet!'),
(377, 4.2, 'Works well for training, easy to use!'),
(378, 4.3, 'Effective brush, my pet loves it!'),
(379, 4.5, 'Bright light, very useful for evening walks!'),
(380, 4.8, 'Makes litter box maintenance so easy!'),
(381, 4.5, 'My pets love it, great product!'),
(382, 4.2, 'Very practical for walks, good size!'),
(383, 4.5, 'Comfortable and adjustable, fits well!'),
(384, 4.6, 'Perfect for my small dog, very comfortable!'),
(385, 4.4, 'Safety first! Works great in the water!'),
(386, 4.5, 'My cat loves this bed, very cozy!'),
(387, 4.3, 'Durable and great for walks, highly recommend!'),
(388, 4.8, 'Essential for pet emergencies, well-stocked!'),
(389, 4.6, 'My dog loves squeaky toys, great fun!'),
(390, 4.5, 'Keeps my home clean, very effective!'),
(391, 4.4, 'Great for hot days, my pet loves it!'),
(392, 4.3, 'My cat loves these, very entertaining!'),
(393, 4.5, 'Keeps food fresh and secure, very useful!'),
(394, 4.2, 'Sustainable and my cat loves it!'),
(395, 4.4, 'Perfect for outdoor play, very effective!'),
(396, 4.5, 'Easy to carry and perfect for travel!'),
(397, 4.3, 'Very practical for travel, my pet loves it!'),
(398, 4.5, 'Great for removing hair, very effective!'),
(399, 4.2, 'Sturdy and functional, great for feeding!'),
(400, 4.8, 'My cat loves chasing the laser, hours of fun!'),
(401, 4.8, 'Excellent quality and comfort, highly recommend!'),
(402, 4.5, 'Sturdy and beautiful, perfect for our dining room.'),
(403, 4.3, 'Very comfortable, great for long hours of work.'),
(404, 4.7, 'Stylish and functional, fits perfectly in my living room.'),
(405, 4.6, 'Modern design, very sleek and elegant.'),
(406, 4.9, 'Very sturdy and easy to assemble, love it!'),
(407, 4.8, 'Spacious and well-built, fits all my clothes.'),
(408, 4.5, 'Very comfortable and looks great in my corner.'),
(409, 4.6, 'Great quality for outdoor use, very sturdy.'),
(410, 4.4, 'Soft and plush, adds a cozy feel to the room.'),
(411, 4.7, 'Gorgeous art piece, I get compliments all the time.'),
(412, 4.5, 'Elegant design, perfect for my bedside table.'),
(413, 4.3, 'Great for blocking light, very stylish.'),
(414, 4.5, 'Excellent for checking outfits, sturdy.'),
(415, 4.2, 'Adds life to my living space, very low maintenance.'),
(416, 4.6, 'Brightens up my sofa, good quality fabric.'),
(417, 4.4, 'Beautiful design, fits perfectly on my table.'),
(418, 4.5, 'Stylish and functional, great addition to my wall.'),
(419, 4.3, 'Scented and lasts long, perfect for relaxation.'),
(420, 4.5, 'Very durable, makes gardening easier.'),
(421, 4.4, 'A must-have for planting, very handy.'),
(422, 4.6, 'Sharp and effective, makes trimming easy.'),
(423, 4.5, 'Strong and well-made, helps with garden maintenance.'),
(424, 4.3, 'Lightweight and easy to use, great design.'),
(425, 4.4, 'Good quality hose, easy to handle.'),
(426, 4.5, 'Perfect for my plants, looks great too.'),
(427, 4.2, 'Very useful for composting, sturdy.'),
(428, 4.3, 'Comfortable and durable, great for gardening.'),
(429, 4.4, 'Evenly spreads fertilizer, good quality.'),
(430, 4.6, 'Very practical for kitchen use, good material.'),
(431, 4.8, 'Non-stick and easy to clean, love it!'),
(432, 4.5, 'Makes smoothies in no time, powerful blender.'),
(433, 4.7, 'Elegant and classy, perfect for family meals.'),
(434, 4.5, 'Accurate measurements, very useful.'),
(435, 4.4, 'Rotates well, keeps my spices organized.'),
(436, 4.6, 'Great for keeping food fresh, good quality.'),
(437, 4.5, 'Protects my hands, very effective.'),
(438, 4.6, 'Stylish and durable, great for dining.'),
(439, 4.7, 'Makes brewing easy, excellent quality.'),
(440, 4.9, 'Fantastic features and user-friendly.'),
(441, 4.6, 'Very useful for tracking my activities.'),
(442, 4.8, 'Great sound quality, very comfortable.'),
(443, 4.5, 'Amazing technology, fun to use.'),
(444, 4.7, 'Incredible experience, love the immersion.'),
(445, 4.4, 'Very handy for health tracking, good design.'),
(446, 4.5, 'Effective and stylish, good addition.'),
(447, 4.3, 'Helps me track sleep well, comfortable.'),
(448, 4.4, 'Charges my devices quickly, compact design.'),
(449, 4.8, 'Saves time and effort, very efficient.'),
(450, 4.7, 'Healthy cooking made easy, love it!'),
(451, 4.5, 'Perfect size for small kitchens, easy to use.'),
(452, 4.9, 'Great capacity and energy-efficient, highly recommend!'),
(453, 4.6, 'Works well, easy to load and unload.'),
(454, 4.4, 'Boils water quickly, very convenient.'),
(455, 4.8, 'Cleans dishes well, a kitchen must-have.'),
(456, 4.5, 'Easy to use, great for quick meals.'),
(457, 4.3, 'Very effective, removes wrinkles easily.'),
(458, 4.6, 'Versatile and powerful, love the grinding feature.'),
(459, 4.4, 'Very useful, adjustable and sturdy.'),
(460, 4.5, 'Great protection for my phone, easy to apply.'),
(461, 4.7, 'Fast charging, very convenient to use.'),
(462, 4.6, 'Stylish and protective, fits perfectly.'),
(463, 4.8, 'Amazing sound quality, very portable.'),
(464, 4.5, 'Compact and handy, great for travel.'),
(465, 4.4, 'Sturdy and reliable, good for car use.'),
(466, 4.3, 'Adjustable and comfortable, great for workouts.'),
(467, 4.5, 'Works perfectly on my tablet, very precise.'),
(468, 4.6, 'Great for stabilizing shots, easy to use.'),
(469, 4.4, 'Fun to use, great for selfies!'),
(470, 4.3, 'Effective for cleaning, very handy.'),
(471, 4.8, 'Very comfortable, perfect for relaxing.'),
(472, 4.5, 'Good quality, perfect for family meals.'),
(473, 4.9, 'Makes perfect espresso, very happy with it.'),
(474, 4.6, 'Very convenient, saves time in the kitchen.'),
(475, 4.7, 'Sharp and effective, essential for cooking.'),
(476, 4.5, 'Great quality, very durable.'),
(477, 4.4, 'Easy to use, makes salad prep quick.'),
(478, 4.6, 'Very versatile, saves a lot of time.'),
(479, 4.5, 'Smart lighting solution, easy to install.'),
(480, 4.8, 'Improves air quality significantly, highly recommended.'),
(481, 4.6, 'Works well, helps control humidity.'),
(482, 4.9, 'Amazing features, worth the investment.'),
(483, 4.8, 'Great cooking experience, love the smart features.'),
(484, 4.5, 'Cuts down cooking time significantly.'),
(485, 4.7, 'Cools down small spaces efficiently.'),
(486, 4.5, 'Great for indoor grilling, very easy to use.'),
(487, 4.6, 'Accurate readings, very helpful in the kitchen.'),
(488, 4.4, 'Great organization tool, eco-friendly materials.'),
(489, 4.5, 'Stylish and functional, great for display.'),
(490, 4.3, 'Looks real, very low maintenance.'),
(491, 4.6, 'Great for displaying memories, sturdy.'),
(492, 4.5, 'Very convenient for hose storage, easy to use.'),
(493, 4.7, 'Sharp and durable, makes trimming easy.'),
(494, 4.4, 'Helps keep my plants watered, very useful.'),
(495, 4.6, 'Very comfortable, makes gardening easier.'),
(496, 4.8, 'Perfect for stabilizing videos, very useful.'),
(497, 4.9, 'Great sound and fit, very happy with them.'),
(498, 4.7, 'Tracks fitness accurately, very comfortable.'),
(499, 4.5, 'Helps me keep track of weight, good features.'),
(500, 4.6, 'Amazing for VR experiences, very immersive.');



