CREATE TABLE orders (
    order_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    product_id INT NOT NULL,
    order_status_id INT NOT NULL,
    order_status_name VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO orders (product_id, order_status_id, order_status_name) VALUES
(1, 1, 'waiting for confirm'),
(2, 2, 'confirmed'),
(3, 3, 'package done'),
(4, 4, 'ready for shipping'),
(5, 5, 'delivered'),
(6, 0, 'cancelled'),
(7, 1, 'waiting for confirm'),
(8, 2, 'confirmed'),
(9, 3, 'package done'),
(10, 4, 'ready for shipping'),
(11, 5, 'delivered'),
(12, 0, 'cancelled'),
(13, 1, 'waiting for confirm'),
(14, 2, 'confirmed'),
(15, 3, 'package done'),
(16, 4, 'ready for shipping'),
(17, 5, 'delivered'),
(18, 0, 'cancelled'),
(19, 1, 'waiting for confirm'),
(20, 2, 'confirmed'),
(21, 3, 'package done'),
(22, 4, 'ready for shipping'),
(23, 5, 'delivered'),
(24, 0, 'cancelled'),
(25, 1, 'waiting for confirm'),
(26, 2, 'confirmed'),
(27, 3, 'package done'),
(28, 4, 'ready for shipping'),
(29, 5, 'delivered'),
(30, 0, 'cancelled');
